/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Cover,
  CoverInternalErrorResponse,
  CoverNotFoundErrorResponse,
} from "../../model";

/**
 * @summary Get Cover
 */
export type getCoverIdResponse200 = {
  data: Cover;
  status: 200;
};

export type getCoverIdResponse404 = {
  data: CoverNotFoundErrorResponse;
  status: 404;
};

export type getCoverIdResponse500 = {
  data: CoverInternalErrorResponse;
  status: 500;
};

export type getCoverIdResponseSuccess = getCoverIdResponse200 & {
  headers: Headers;
};
export type getCoverIdResponseError = (
  | getCoverIdResponse404
  | getCoverIdResponse500
) & {
  headers: Headers;
};

export type getCoverIdResponse =
  | getCoverIdResponseSuccess
  | getCoverIdResponseError;

export const getGetCoverIdUrl = (id: string) => {
  return `https://wd.suicaodex.com/cover/${id}`;
};

export const getCoverId = async (
  id: string,
  options?: RequestInit,
): Promise<getCoverIdResponse> => {
  const res = await fetch(getGetCoverIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCoverIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCoverIdResponse;
};

export const getGetCoverIdQueryKey = (id: string) => {
  return [`https://wd.suicaodex.com/cover/${id}`] as const;
};

export const getGetCoverIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoverId>>,
  TError = CoverNotFoundErrorResponse | CoverInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoverId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoverIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoverId>>> = ({
    signal,
  }) => getCoverId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoverId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoverIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoverId>>
>;
export type GetCoverIdQueryError =
  | CoverNotFoundErrorResponse
  | CoverInternalErrorResponse;

export function useGetCoverId<
  TData = Awaited<ReturnType<typeof getCoverId>>,
  TError = CoverNotFoundErrorResponse | CoverInternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoverId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoverId>>,
          TError,
          Awaited<ReturnType<typeof getCoverId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoverId<
  TData = Awaited<ReturnType<typeof getCoverId>>,
  TError = CoverNotFoundErrorResponse | CoverInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoverId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoverId>>,
          TError,
          Awaited<ReturnType<typeof getCoverId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoverId<
  TData = Awaited<ReturnType<typeof getCoverId>>,
  TError = CoverNotFoundErrorResponse | CoverInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoverId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Cover
 */

export function useGetCoverId<
  TData = Awaited<ReturnType<typeof getCoverId>>,
  TError = CoverNotFoundErrorResponse | CoverInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoverId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoverIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
