/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ControllersImportFollowedMangaRequest,
  ControllersUpdateMangaFollowRequest,
  GetUserFollowsChapterFeedParams,
  GetUserFollowsGroupsParams,
  GetUserFollowsMangaParams,
  GetUserFollowsUsersParams,
  GroupFollowFeedResponse,
  MangaFollowFeedResponse,
  MappedChapterFeedResponse,
  UserFollowFeedResponse,
} from "../../model";

/**
 * @summary [Manga] Get Latest Feed
 */
export type getUserFollowsChapterFeedResponse200 = {
  data: MappedChapterFeedResponse;
  status: 200;
};

export type getUserFollowsChapterFeedResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsChapterFeedResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsChapterFeedResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsChapterFeedResponseSuccess =
  getUserFollowsChapterFeedResponse200 & {
    headers: Headers;
  };
export type getUserFollowsChapterFeedResponseError = (
  | getUserFollowsChapterFeedResponse400
  | getUserFollowsChapterFeedResponse403
  | getUserFollowsChapterFeedResponse500
) & {
  headers: Headers;
};

export type getUserFollowsChapterFeedResponse =
  | getUserFollowsChapterFeedResponseSuccess
  | getUserFollowsChapterFeedResponseError;

export const getGetUserFollowsChapterFeedUrl = (
  params?: GetUserFollowsChapterFeedParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/user/follows/chapter/feed?${stringifiedParams}`
    : `https://wd.memaydex.online/user/follows/chapter/feed`;
};

export const getUserFollowsChapterFeed = async (
  params?: GetUserFollowsChapterFeedParams,
  options?: RequestInit,
): Promise<getUserFollowsChapterFeedResponse> => {
  const res = await fetch(getGetUserFollowsChapterFeedUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsChapterFeedResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsChapterFeedResponse;
};

export const getGetUserFollowsChapterFeedQueryKey = (
  params?: GetUserFollowsChapterFeedParams,
) => {
  return [
    `https://wd.memaydex.online/user/follows/chapter/feed`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetUserFollowsChapterFeedQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
  TError = void,
>(
  params?: GetUserFollowsChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsChapterFeedQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsChapterFeed>>
  > = ({ signal }) =>
    getUserFollowsChapterFeed(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsChapterFeedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsChapterFeed>>
>;
export type GetUserFollowsChapterFeedQueryError = void;

export function useGetUserFollowsChapterFeed<
  TData = Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
  TError = void,
>(
  params: undefined | GetUserFollowsChapterFeedParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsChapterFeed>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsChapterFeed<
  TData = Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
  TError = void,
>(
  params?: GetUserFollowsChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsChapterFeed>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsChapterFeed<
  TData = Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
  TError = void,
>(
  params?: GetUserFollowsChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [Manga] Get Latest Feed
 */

export function useGetUserFollowsChapterFeed<
  TData = Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
  TError = void,
>(
  params?: GetUserFollowsChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsChapterFeed>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsChapterFeedQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [Group] Search
 */
export type getUserFollowsGroupsResponse200 = {
  data: GroupFollowFeedResponse;
  status: 200;
};

export type getUserFollowsGroupsResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsGroupsResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsGroupsResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsGroupsResponseSuccess =
  getUserFollowsGroupsResponse200 & {
    headers: Headers;
  };
export type getUserFollowsGroupsResponseError = (
  | getUserFollowsGroupsResponse400
  | getUserFollowsGroupsResponse403
  | getUserFollowsGroupsResponse500
) & {
  headers: Headers;
};

export type getUserFollowsGroupsResponse =
  | getUserFollowsGroupsResponseSuccess
  | getUserFollowsGroupsResponseError;

export const getGetUserFollowsGroupsUrl = (
  params?: GetUserFollowsGroupsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/user/follows/groups?${stringifiedParams}`
    : `https://wd.memaydex.online/user/follows/groups`;
};

export const getUserFollowsGroups = async (
  params?: GetUserFollowsGroupsParams,
  options?: RequestInit,
): Promise<getUserFollowsGroupsResponse> => {
  const res = await fetch(getGetUserFollowsGroupsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsGroupsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsGroupsResponse;
};

export const getGetUserFollowsGroupsQueryKey = (
  params?: GetUserFollowsGroupsParams,
) => {
  return [
    `https://wd.memaydex.online/user/follows/groups`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetUserFollowsGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsGroups>>,
  TError = void,
>(
  params?: GetUserFollowsGroupsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroups>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsGroupsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsGroups>>
  > = ({ signal }) => getUserFollowsGroups(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsGroups>>
>;
export type GetUserFollowsGroupsQueryError = void;

export function useGetUserFollowsGroups<
  TData = Awaited<ReturnType<typeof getUserFollowsGroups>>,
  TError = void,
>(
  params: undefined | GetUserFollowsGroupsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsGroups>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsGroups>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsGroups<
  TData = Awaited<ReturnType<typeof getUserFollowsGroups>>,
  TError = void,
>(
  params?: GetUserFollowsGroupsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsGroups>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsGroups>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsGroups<
  TData = Awaited<ReturnType<typeof getUserFollowsGroups>>,
  TError = void,
>(
  params?: GetUserFollowsGroupsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroups>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [Group] Search
 */

export function useGetUserFollowsGroups<
  TData = Awaited<ReturnType<typeof getUserFollowsGroups>>,
  TError = void,
>(
  params?: GetUserFollowsGroupsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroups>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsGroupsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [Group] Get Follow Status
 */
export type getUserFollowsGroupsIdResponse204 = {
  data: void;
  status: 204;
};

export type getUserFollowsGroupsIdResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsGroupsIdResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsGroupsIdResponse404 = {
  data: void;
  status: 404;
};

export type getUserFollowsGroupsIdResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsGroupsIdResponseSuccess =
  getUserFollowsGroupsIdResponse204 & {
    headers: Headers;
  };
export type getUserFollowsGroupsIdResponseError = (
  | getUserFollowsGroupsIdResponse400
  | getUserFollowsGroupsIdResponse403
  | getUserFollowsGroupsIdResponse404
  | getUserFollowsGroupsIdResponse500
) & {
  headers: Headers;
};

export type getUserFollowsGroupsIdResponse =
  | getUserFollowsGroupsIdResponseSuccess
  | getUserFollowsGroupsIdResponseError;

export const getGetUserFollowsGroupsIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/groups/${id}`;
};

export const getUserFollowsGroupsId = async (
  id: string,
  options?: RequestInit,
): Promise<getUserFollowsGroupsIdResponse> => {
  const res = await fetch(getGetUserFollowsGroupsIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsGroupsIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsGroupsIdResponse;
};

export const getGetUserFollowsGroupsIdQueryKey = (id: string) => {
  return [`https://wd.memaydex.online/user/follows/groups/${id}`] as const;
};

export const getGetUserFollowsGroupsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsGroupsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsGroupsId>>
  > = ({ signal }) => getUserFollowsGroupsId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsGroupsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsGroupsId>>
>;
export type GetUserFollowsGroupsIdQueryError = void;

export function useGetUserFollowsGroupsId<
  TData = Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsGroupsId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsGroupsId<
  TData = Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsGroupsId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsGroupsId<
  TData = Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [Group] Get Follow Status
 */

export function useGetUserFollowsGroupsId<
  TData = Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsGroupsId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsGroupsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [Group] Follow
 */
export type postUserFollowsGroupsIdResponse204 = {
  data: void;
  status: 204;
};

export type postUserFollowsGroupsIdResponse400 = {
  data: void;
  status: 400;
};

export type postUserFollowsGroupsIdResponse403 = {
  data: void;
  status: 403;
};

export type postUserFollowsGroupsIdResponse409 = {
  data: void;
  status: 409;
};

export type postUserFollowsGroupsIdResponse500 = {
  data: void;
  status: 500;
};

export type postUserFollowsGroupsIdResponseSuccess =
  postUserFollowsGroupsIdResponse204 & {
    headers: Headers;
  };
export type postUserFollowsGroupsIdResponseError = (
  | postUserFollowsGroupsIdResponse400
  | postUserFollowsGroupsIdResponse403
  | postUserFollowsGroupsIdResponse409
  | postUserFollowsGroupsIdResponse500
) & {
  headers: Headers;
};

export type postUserFollowsGroupsIdResponse =
  | postUserFollowsGroupsIdResponseSuccess
  | postUserFollowsGroupsIdResponseError;

export const getPostUserFollowsGroupsIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/groups/${id}`;
};

export const postUserFollowsGroupsId = async (
  id: string,
  options?: RequestInit,
): Promise<postUserFollowsGroupsIdResponse> => {
  const res = await fetch(getPostUserFollowsGroupsIdUrl(id), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUserFollowsGroupsIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postUserFollowsGroupsIdResponse;
};

export const getPostUserFollowsGroupsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUserFollowsGroupsId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUserFollowsGroupsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["postUserFollowsGroupsId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUserFollowsGroupsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postUserFollowsGroupsId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUserFollowsGroupsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUserFollowsGroupsId>>
>;

export type PostUserFollowsGroupsIdMutationError = void;

/**
 * @summary [Group] Follow
 */
export const usePostUserFollowsGroupsId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUserFollowsGroupsId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUserFollowsGroupsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostUserFollowsGroupsIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [Group] Unfollow
 */
export type deleteUserFollowsGroupsIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteUserFollowsGroupsIdResponse400 = {
  data: void;
  status: 400;
};

export type deleteUserFollowsGroupsIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteUserFollowsGroupsIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteUserFollowsGroupsIdResponse500 = {
  data: void;
  status: 500;
};

export type deleteUserFollowsGroupsIdResponseSuccess =
  deleteUserFollowsGroupsIdResponse204 & {
    headers: Headers;
  };
export type deleteUserFollowsGroupsIdResponseError = (
  | deleteUserFollowsGroupsIdResponse400
  | deleteUserFollowsGroupsIdResponse403
  | deleteUserFollowsGroupsIdResponse404
  | deleteUserFollowsGroupsIdResponse500
) & {
  headers: Headers;
};

export type deleteUserFollowsGroupsIdResponse =
  | deleteUserFollowsGroupsIdResponseSuccess
  | deleteUserFollowsGroupsIdResponseError;

export const getDeleteUserFollowsGroupsIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/groups/${id}`;
};

export const deleteUserFollowsGroupsId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserFollowsGroupsIdResponse> => {
  const res = await fetch(getDeleteUserFollowsGroupsIdUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserFollowsGroupsIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUserFollowsGroupsIdResponse;
};

export const getDeleteUserFollowsGroupsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteUserFollowsGroupsId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserFollowsGroupsId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserFollowsGroupsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>
>;

export type DeleteUserFollowsGroupsIdMutationError = void;

/**
 * @summary [Group] Unfollow
 */
export const useDeleteUserFollowsGroupsId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserFollowsGroupsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteUserFollowsGroupsIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [Manga] Search
 */
export type getUserFollowsMangaResponse200 = {
  data: MangaFollowFeedResponse;
  status: 200;
};

export type getUserFollowsMangaResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsMangaResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsMangaResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsMangaResponseSuccess =
  getUserFollowsMangaResponse200 & {
    headers: Headers;
  };
export type getUserFollowsMangaResponseError = (
  | getUserFollowsMangaResponse400
  | getUserFollowsMangaResponse403
  | getUserFollowsMangaResponse500
) & {
  headers: Headers;
};

export type getUserFollowsMangaResponse =
  | getUserFollowsMangaResponseSuccess
  | getUserFollowsMangaResponseError;

export const getGetUserFollowsMangaUrl = (
  params?: GetUserFollowsMangaParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/user/follows/manga?${stringifiedParams}`
    : `https://wd.memaydex.online/user/follows/manga`;
};

export const getUserFollowsManga = async (
  params?: GetUserFollowsMangaParams,
  options?: RequestInit,
): Promise<getUserFollowsMangaResponse> => {
  const res = await fetch(getGetUserFollowsMangaUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsMangaResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsMangaResponse;
};

export const getGetUserFollowsMangaQueryKey = (
  params?: GetUserFollowsMangaParams,
) => {
  return [
    `https://wd.memaydex.online/user/follows/manga`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetUserFollowsMangaQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsManga>>,
  TError = void,
>(
  params?: GetUserFollowsMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsManga>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsMangaQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsManga>>
  > = ({ signal }) => getUserFollowsManga(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsManga>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsMangaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsManga>>
>;
export type GetUserFollowsMangaQueryError = void;

export function useGetUserFollowsManga<
  TData = Awaited<ReturnType<typeof getUserFollowsManga>>,
  TError = void,
>(
  params: undefined | GetUserFollowsMangaParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsManga>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsManga>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsManga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsManga<
  TData = Awaited<ReturnType<typeof getUserFollowsManga>>,
  TError = void,
>(
  params?: GetUserFollowsMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsManga>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsManga>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsManga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsManga<
  TData = Awaited<ReturnType<typeof getUserFollowsManga>>,
  TError = void,
>(
  params?: GetUserFollowsMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsManga>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [Manga] Search
 */

export function useGetUserFollowsManga<
  TData = Awaited<ReturnType<typeof getUserFollowsManga>>,
  TError = void,
>(
  params?: GetUserFollowsMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsManga>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsMangaQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [Manga] Export
 */
export type getUserFollowsMangaExportResponse200 = {
  data: string;
  status: 200;
};

export type getUserFollowsMangaExportResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsMangaExportResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsMangaExportResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsMangaExportResponseSuccess =
  getUserFollowsMangaExportResponse200 & {
    headers: Headers;
  };
export type getUserFollowsMangaExportResponseError = (
  | getUserFollowsMangaExportResponse400
  | getUserFollowsMangaExportResponse403
  | getUserFollowsMangaExportResponse500
) & {
  headers: Headers;
};

export type getUserFollowsMangaExportResponse =
  | getUserFollowsMangaExportResponseSuccess
  | getUserFollowsMangaExportResponseError;

export const getGetUserFollowsMangaExportUrl = () => {
  return `https://wd.memaydex.online/user/follows/manga/export`;
};

export const getUserFollowsMangaExport = async (
  options?: RequestInit,
): Promise<getUserFollowsMangaExportResponse> => {
  const res = await fetch(getGetUserFollowsMangaExportUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsMangaExportResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsMangaExportResponse;
};

export const getGetUserFollowsMangaExportQueryKey = () => {
  return [`https://wd.memaydex.online/user/follows/manga/export`] as const;
};

export const getGetUserFollowsMangaExportQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsMangaExportQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsMangaExport>>
  > = ({ signal }) => getUserFollowsMangaExport({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsMangaExportQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsMangaExport>>
>;
export type GetUserFollowsMangaExportQueryError = void;

export function useGetUserFollowsMangaExport<
  TData = Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsMangaExport>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsMangaExport<
  TData = Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsMangaExport>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsMangaExport<
  TData = Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [Manga] Export
 */

export function useGetUserFollowsMangaExport<
  TData = Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsMangaExport>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsMangaExportQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [Manga] Import
 */
export type postUserFollowsMangaImportResponse204 = {
  data: void;
  status: 204;
};

export type postUserFollowsMangaImportResponse400 = {
  data: void;
  status: 400;
};

export type postUserFollowsMangaImportResponse403 = {
  data: void;
  status: 403;
};

export type postUserFollowsMangaImportResponse500 = {
  data: void;
  status: 500;
};

export type postUserFollowsMangaImportResponseSuccess =
  postUserFollowsMangaImportResponse204 & {
    headers: Headers;
  };
export type postUserFollowsMangaImportResponseError = (
  | postUserFollowsMangaImportResponse400
  | postUserFollowsMangaImportResponse403
  | postUserFollowsMangaImportResponse500
) & {
  headers: Headers;
};

export type postUserFollowsMangaImportResponse =
  | postUserFollowsMangaImportResponseSuccess
  | postUserFollowsMangaImportResponseError;

export const getPostUserFollowsMangaImportUrl = () => {
  return `https://wd.memaydex.online/user/follows/manga/import`;
};

export const postUserFollowsMangaImport = async (
  controllersImportFollowedMangaRequest: ControllersImportFollowedMangaRequest,
  options?: RequestInit,
): Promise<postUserFollowsMangaImportResponse> => {
  const res = await fetch(getPostUserFollowsMangaImportUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersImportFollowedMangaRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUserFollowsMangaImportResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postUserFollowsMangaImportResponse;
};

export const getPostUserFollowsMangaImportMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUserFollowsMangaImport>>,
    TError,
    { data: ControllersImportFollowedMangaRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUserFollowsMangaImport>>,
  TError,
  { data: ControllersImportFollowedMangaRequest },
  TContext
> => {
  const mutationKey = ["postUserFollowsMangaImport"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUserFollowsMangaImport>>,
    { data: ControllersImportFollowedMangaRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postUserFollowsMangaImport(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUserFollowsMangaImportMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUserFollowsMangaImport>>
>;
export type PostUserFollowsMangaImportMutationBody =
  ControllersImportFollowedMangaRequest;
export type PostUserFollowsMangaImportMutationError = void;

/**
 * @summary [Manga] Import
 */
export const usePostUserFollowsMangaImport = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUserFollowsMangaImport>>,
      TError,
      { data: ControllersImportFollowedMangaRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUserFollowsMangaImport>>,
  TError,
  { data: ControllersImportFollowedMangaRequest },
  TContext
> => {
  return useMutation(
    getPostUserFollowsMangaImportMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [Manga] Update Follow Status
 */
export type postUserFollowsMangaIdResponse204 = {
  data: void;
  status: 204;
};

export type postUserFollowsMangaIdResponse400 = {
  data: void;
  status: 400;
};

export type postUserFollowsMangaIdResponse403 = {
  data: void;
  status: 403;
};

export type postUserFollowsMangaIdResponse404 = {
  data: void;
  status: 404;
};

export type postUserFollowsMangaIdResponse500 = {
  data: void;
  status: 500;
};

export type postUserFollowsMangaIdResponseSuccess =
  postUserFollowsMangaIdResponse204 & {
    headers: Headers;
  };
export type postUserFollowsMangaIdResponseError = (
  | postUserFollowsMangaIdResponse400
  | postUserFollowsMangaIdResponse403
  | postUserFollowsMangaIdResponse404
  | postUserFollowsMangaIdResponse500
) & {
  headers: Headers;
};

export type postUserFollowsMangaIdResponse =
  | postUserFollowsMangaIdResponseSuccess
  | postUserFollowsMangaIdResponseError;

export const getPostUserFollowsMangaIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/manga/${id}`;
};

export const postUserFollowsMangaId = async (
  id: string,
  controllersUpdateMangaFollowRequest: ControllersUpdateMangaFollowRequest,
  options?: RequestInit,
): Promise<postUserFollowsMangaIdResponse> => {
  const res = await fetch(getPostUserFollowsMangaIdUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersUpdateMangaFollowRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUserFollowsMangaIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postUserFollowsMangaIdResponse;
};

export const getPostUserFollowsMangaIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUserFollowsMangaId>>,
    TError,
    { id: string; data: ControllersUpdateMangaFollowRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUserFollowsMangaId>>,
  TError,
  { id: string; data: ControllersUpdateMangaFollowRequest },
  TContext
> => {
  const mutationKey = ["postUserFollowsMangaId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUserFollowsMangaId>>,
    { id: string; data: ControllersUpdateMangaFollowRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postUserFollowsMangaId(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUserFollowsMangaIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUserFollowsMangaId>>
>;
export type PostUserFollowsMangaIdMutationBody =
  ControllersUpdateMangaFollowRequest;
export type PostUserFollowsMangaIdMutationError = void;

/**
 * @summary [Manga] Update Follow Status
 */
export const usePostUserFollowsMangaId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUserFollowsMangaId>>,
      TError,
      { id: string; data: ControllersUpdateMangaFollowRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUserFollowsMangaId>>,
  TError,
  { id: string; data: ControllersUpdateMangaFollowRequest },
  TContext
> => {
  return useMutation(
    getPostUserFollowsMangaIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [Manga] Unfollow
 */
export type deleteUserFollowsMangaIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteUserFollowsMangaIdResponse400 = {
  data: void;
  status: 400;
};

export type deleteUserFollowsMangaIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteUserFollowsMangaIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteUserFollowsMangaIdResponse500 = {
  data: void;
  status: 500;
};

export type deleteUserFollowsMangaIdResponseSuccess =
  deleteUserFollowsMangaIdResponse204 & {
    headers: Headers;
  };
export type deleteUserFollowsMangaIdResponseError = (
  | deleteUserFollowsMangaIdResponse400
  | deleteUserFollowsMangaIdResponse403
  | deleteUserFollowsMangaIdResponse404
  | deleteUserFollowsMangaIdResponse500
) & {
  headers: Headers;
};

export type deleteUserFollowsMangaIdResponse =
  | deleteUserFollowsMangaIdResponseSuccess
  | deleteUserFollowsMangaIdResponseError;

export const getDeleteUserFollowsMangaIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/manga/${id}`;
};

export const deleteUserFollowsMangaId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserFollowsMangaIdResponse> => {
  const res = await fetch(getDeleteUserFollowsMangaIdUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserFollowsMangaIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUserFollowsMangaIdResponse;
};

export const getDeleteUserFollowsMangaIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserFollowsMangaId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserFollowsMangaId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteUserFollowsMangaId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserFollowsMangaId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserFollowsMangaId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserFollowsMangaIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserFollowsMangaId>>
>;

export type DeleteUserFollowsMangaIdMutationError = void;

/**
 * @summary [Manga] Unfollow
 */
export const useDeleteUserFollowsMangaId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserFollowsMangaId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserFollowsMangaId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteUserFollowsMangaIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [User] Search
 */
export type getUserFollowsUsersResponse200 = {
  data: UserFollowFeedResponse;
  status: 200;
};

export type getUserFollowsUsersResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsUsersResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsUsersResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsUsersResponseSuccess =
  getUserFollowsUsersResponse200 & {
    headers: Headers;
  };
export type getUserFollowsUsersResponseError = (
  | getUserFollowsUsersResponse400
  | getUserFollowsUsersResponse403
  | getUserFollowsUsersResponse500
) & {
  headers: Headers;
};

export type getUserFollowsUsersResponse =
  | getUserFollowsUsersResponseSuccess
  | getUserFollowsUsersResponseError;

export const getGetUserFollowsUsersUrl = (
  params?: GetUserFollowsUsersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/user/follows/users?${stringifiedParams}`
    : `https://wd.memaydex.online/user/follows/users`;
};

export const getUserFollowsUsers = async (
  params?: GetUserFollowsUsersParams,
  options?: RequestInit,
): Promise<getUserFollowsUsersResponse> => {
  const res = await fetch(getGetUserFollowsUsersUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsUsersResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsUsersResponse;
};

export const getGetUserFollowsUsersQueryKey = (
  params?: GetUserFollowsUsersParams,
) => {
  return [
    `https://wd.memaydex.online/user/follows/users`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetUserFollowsUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsUsers>>,
  TError = void,
>(
  params?: GetUserFollowsUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsers>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsUsers>>
  > = ({ signal }) => getUserFollowsUsers(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsUsers>>
>;
export type GetUserFollowsUsersQueryError = void;

export function useGetUserFollowsUsers<
  TData = Awaited<ReturnType<typeof getUserFollowsUsers>>,
  TError = void,
>(
  params: undefined | GetUserFollowsUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsUsers>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsUsers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsUsers<
  TData = Awaited<ReturnType<typeof getUserFollowsUsers>>,
  TError = void,
>(
  params?: GetUserFollowsUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsUsers>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsUsers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsUsers<
  TData = Awaited<ReturnType<typeof getUserFollowsUsers>>,
  TError = void,
>(
  params?: GetUserFollowsUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsers>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [User] Search
 */

export function useGetUserFollowsUsers<
  TData = Awaited<ReturnType<typeof getUserFollowsUsers>>,
  TError = void,
>(
  params?: GetUserFollowsUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsers>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsUsersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [User] Get Follow Status
 */
export type getUserFollowsUsersIdResponse204 = {
  data: void;
  status: 204;
};

export type getUserFollowsUsersIdResponse400 = {
  data: void;
  status: 400;
};

export type getUserFollowsUsersIdResponse403 = {
  data: void;
  status: 403;
};

export type getUserFollowsUsersIdResponse404 = {
  data: void;
  status: 404;
};

export type getUserFollowsUsersIdResponse500 = {
  data: void;
  status: 500;
};

export type getUserFollowsUsersIdResponseSuccess =
  getUserFollowsUsersIdResponse204 & {
    headers: Headers;
  };
export type getUserFollowsUsersIdResponseError = (
  | getUserFollowsUsersIdResponse400
  | getUserFollowsUsersIdResponse403
  | getUserFollowsUsersIdResponse404
  | getUserFollowsUsersIdResponse500
) & {
  headers: Headers;
};

export type getUserFollowsUsersIdResponse =
  | getUserFollowsUsersIdResponseSuccess
  | getUserFollowsUsersIdResponseError;

export const getGetUserFollowsUsersIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/users/${id}`;
};

export const getUserFollowsUsersId = async (
  id: string,
  options?: RequestInit,
): Promise<getUserFollowsUsersIdResponse> => {
  const res = await fetch(getGetUserFollowsUsersIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserFollowsUsersIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserFollowsUsersIdResponse;
};

export const getGetUserFollowsUsersIdQueryKey = (id: string) => {
  return [`https://wd.memaydex.online/user/follows/users/${id}`] as const;
};

export const getGetUserFollowsUsersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserFollowsUsersId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsersId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserFollowsUsersIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserFollowsUsersId>>
  > = ({ signal }) => getUserFollowsUsersId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserFollowsUsersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserFollowsUsersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserFollowsUsersId>>
>;
export type GetUserFollowsUsersIdQueryError = void;

export function useGetUserFollowsUsersId<
  TData = Awaited<ReturnType<typeof getUserFollowsUsersId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsersId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsUsersId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsUsersId<
  TData = Awaited<ReturnType<typeof getUserFollowsUsersId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsersId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFollowsUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUserFollowsUsersId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserFollowsUsersId<
  TData = Awaited<ReturnType<typeof getUserFollowsUsersId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsersId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary [User] Get Follow Status
 */

export function useGetUserFollowsUsersId<
  TData = Awaited<ReturnType<typeof getUserFollowsUsersId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserFollowsUsersId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserFollowsUsersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary [User] Follow
 */
export type postUserFollowsUsersIdResponse204 = {
  data: void;
  status: 204;
};

export type postUserFollowsUsersIdResponse400 = {
  data: void;
  status: 400;
};

export type postUserFollowsUsersIdResponse403 = {
  data: void;
  status: 403;
};

export type postUserFollowsUsersIdResponse409 = {
  data: void;
  status: 409;
};

export type postUserFollowsUsersIdResponse500 = {
  data: void;
  status: 500;
};

export type postUserFollowsUsersIdResponseSuccess =
  postUserFollowsUsersIdResponse204 & {
    headers: Headers;
  };
export type postUserFollowsUsersIdResponseError = (
  | postUserFollowsUsersIdResponse400
  | postUserFollowsUsersIdResponse403
  | postUserFollowsUsersIdResponse409
  | postUserFollowsUsersIdResponse500
) & {
  headers: Headers;
};

export type postUserFollowsUsersIdResponse =
  | postUserFollowsUsersIdResponseSuccess
  | postUserFollowsUsersIdResponseError;

export const getPostUserFollowsUsersIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/users/${id}`;
};

export const postUserFollowsUsersId = async (
  id: string,
  options?: RequestInit,
): Promise<postUserFollowsUsersIdResponse> => {
  const res = await fetch(getPostUserFollowsUsersIdUrl(id), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUserFollowsUsersIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postUserFollowsUsersIdResponse;
};

export const getPostUserFollowsUsersIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUserFollowsUsersId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUserFollowsUsersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["postUserFollowsUsersId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUserFollowsUsersId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postUserFollowsUsersId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUserFollowsUsersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUserFollowsUsersId>>
>;

export type PostUserFollowsUsersIdMutationError = void;

/**
 * @summary [User] Follow
 */
export const usePostUserFollowsUsersId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUserFollowsUsersId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUserFollowsUsersId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostUserFollowsUsersIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary [User] Unfollow
 */
export type deleteUserFollowsUsersIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteUserFollowsUsersIdResponse400 = {
  data: void;
  status: 400;
};

export type deleteUserFollowsUsersIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteUserFollowsUsersIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteUserFollowsUsersIdResponse500 = {
  data: void;
  status: 500;
};

export type deleteUserFollowsUsersIdResponseSuccess =
  deleteUserFollowsUsersIdResponse204 & {
    headers: Headers;
  };
export type deleteUserFollowsUsersIdResponseError = (
  | deleteUserFollowsUsersIdResponse400
  | deleteUserFollowsUsersIdResponse403
  | deleteUserFollowsUsersIdResponse404
  | deleteUserFollowsUsersIdResponse500
) & {
  headers: Headers;
};

export type deleteUserFollowsUsersIdResponse =
  | deleteUserFollowsUsersIdResponseSuccess
  | deleteUserFollowsUsersIdResponseError;

export const getDeleteUserFollowsUsersIdUrl = (id: string) => {
  return `https://wd.memaydex.online/user/follows/users/${id}`;
};

export const deleteUserFollowsUsersId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteUserFollowsUsersIdResponse> => {
  const res = await fetch(getDeleteUserFollowsUsersIdUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserFollowsUsersIdResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUserFollowsUsersIdResponse;
};

export const getDeleteUserFollowsUsersIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserFollowsUsersId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserFollowsUsersId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteUserFollowsUsersId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserFollowsUsersId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserFollowsUsersId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserFollowsUsersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserFollowsUsersId>>
>;

export type DeleteUserFollowsUsersIdMutationError = void;

/**
 * @summary [User] Unfollow
 */
export const useDeleteUserFollowsUsersId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserFollowsUsersId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserFollowsUsersId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteUserFollowsUsersIdMutationOptions(options),
    queryClient,
  );
};
