/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

Full features will be added in the future (chắc thế)

Github: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api), [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)

NOTE:
- All API endpoints have a global rate limit of 7 requests per second per IP.
- To avoid future issues, include the Origin: https://suicaodex.com or https://moetruyen.net headers when making API requests.
 * OpenAPI spec version: 0.1.0
 */
import type { GetV1MangaSort } from "./getV1MangaSort";
import type { GetV1MangaStatus } from "./getV1MangaStatus";

export type GetV1MangaParams = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @maxLength 100
   */
  q?: string;
  /**
   * @maxLength 100
   */
  genre?: string;
  status?: GetV1MangaStatus;
  sort?: GetV1MangaSort;
};
