/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

## Quick start

Use the `/v1` routes for the current stable surface.
Use the `/v2` manga-family routes for the newer include-based contract.

## Request notes

- All API endpoints have a global rate limit of 7 requests per second per IP.
- Include a valid `Origin` header such as `https://suicaodex.com` or `https://moetruyen.net` when making browser-like requests.
- Query parameters such as `sort`, `order`, `genre`, `genrex`, and `include` are documented per route below.

## Versioning

- `/v1` preserves the original route contracts.
- `/v2` is the forward-looking surface where manga-family routes share a common base object and optional expansions.

## Repositories

- API repo: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api)
- Original site repo: [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)
 * OpenAPI spec version: 0.2.0
 */
import type { GetV2MangaRandom200DataItemGenresItem } from "./getV2MangaRandom200DataItemGenresItem";
import type { GetV2MangaRandom200DataItemStats } from "./getV2MangaRandom200DataItemStats";
import type { GetV2MangaRandom200DataItemStatus } from "./getV2MangaRandom200DataItemStatus";

export type GetV2MangaRandom200DataItem = {
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  id: number;
  /** @minLength 1 */
  slug: string;
  /** @minLength 1 */
  title: string;
  description: string | null;
  author: string | null;
  /** Public manga status. Allowed values: `ongoing`, `completed`, `hiatus`, `cancelled`, `unknown`. */
  status: GetV2MangaRandom200DataItemStatus;
  cover: string | null;
  coverUrl: string | null;
  coverUpdatedAt: string | null;
  groupName: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  isOneshot: boolean;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  chapterCount: number;
  latestChapterNumber: number | null;
  latestChapterNumberText: string | null;
  /** Optional aggregate statistics. Present only when `include=stats` is requested. */
  stats?: GetV2MangaRandom200DataItemStats;
  genres?: GetV2MangaRandom200DataItemGenresItem[];
};
