/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

## Quick start

Use the `/v1` routes for the current stable surface.
Use the `/v2` manga-family routes for the newer include-based contract.

## Request notes

- All API endpoints have a global rate limit of 7 requests per second per IP.
- Include a valid `Origin` header such as `https://suicaodex.com` or `https://moetruyen.net` when making browser-like requests.
- Query parameters such as `sort`, `order`, `genre`, `genrex`, and `include` are documented per route below.

## Versioning

- `/v1` preserves the original route contracts.
- `/v2` is the forward-looking surface where manga-family routes share a common base object and optional expansions.

## Repositories

- API repo: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api)
- Original site repo: [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)
 * OpenAPI spec version: 0.2.0
 */
import type { GetV2TeamsByIdMangaSort } from "./getV2TeamsByIdMangaSort";
import type { GetV2TeamsByIdMangaStatus } from "./getV2TeamsByIdMangaStatus";

export type GetV2TeamsByIdMangaParams = {
  /**
   * Page number starting from `1`.
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * Maximum number of manga items to return per page. Allowed range: `1` to `100`.
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Free-text search term matched against manga title, slug, and aliases.
   * @maxLength 100
   */
  q?: string;
  /**
   * Optional inclusive genre filter for team manga in v2. Accepts comma-separated genre ids with OR semantics.
   */
  genre?: string | number;
  /**
   * Optional manga status filter for the team manga listing.
   */
  status?: GetV2TeamsByIdMangaStatus;
  /**
   * Sort mode. `updated_at` sorts by recent updates, `title` sorts alphabetically, and `popular` sorts by view-derived popularity.
   */
  sort?: GetV2TeamsByIdMangaSort;
  /**
   * Optional exclusion genre filter for team manga in v2. Manga that have any of these genre ids are removed from results.
   */
  genrex?: string | number;
  /**
   * Comma-separated expansions. Supported values: `stats`, `genres`. Example: `stats,genres`.
   */
  include?: string;
};
