/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

Full features will be added in the future (chắc thế)

Github: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api), [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)

NOTE:
- All API endpoints have a global rate limit of 7 requests per second per IP.
- To avoid future issues, include the Origin: https://suicaodex.com or https://moetruyen.net headers when making API requests.
 * OpenAPI spec version: 0.1.0
 */

export type GetV1TeamsSort =
  (typeof GetV1TeamsSort)[keyof typeof GetV1TeamsSort];

export const GetV1TeamsSort = {
  updated_at: "updated_at",
  member_count: "member_count",
  manga_count: "manga_count",
  chapter_count: "chapter_count",
  comment_count: "comment_count",
} as const;
