/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

Full features will be added in the future (chắc thế)

Github: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api), [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)

NOTE:
- All API endpoints have a global rate limit of 7 requests per second per IP.
- To avoid future issues, include the Origin: https://suicaodex.com or https://moetruyen.net headers when making API requests.
 * OpenAPI spec version: 0.1.0
 */
import type { GetV1ChaptersById200DataChapter } from "./getV1ChaptersById200DataChapter";
import type { GetV1ChaptersById200DataManga } from "./getV1ChaptersById200DataManga";
import type { GetV1ChaptersById200DataNextChapter } from "./getV1ChaptersById200DataNextChapter";
import type { GetV1ChaptersById200DataPrevChapter } from "./getV1ChaptersById200DataPrevChapter";

export type GetV1ChaptersById200Data = {
  manga: GetV1ChaptersById200DataManga;
  chapter: GetV1ChaptersById200DataChapter;
  pageUrls: string[];
  prevChapter: GetV1ChaptersById200DataPrevChapter;
  nextChapter: GetV1ChaptersById200DataNextChapter;
};
