/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

Full features will be added in the future (chắc thế)

Github: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api), [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)

NOTE:
- All API endpoints have a global rate limit of 7 requests per second per IP.
- To avoid future issues, include the Origin: https://suicaodex.com or https://moetruyen.net headers when making API requests.
 * OpenAPI spec version: 0.1.0
 */
import type { GetV1TeamsByIdMembers400Error } from "./getV1TeamsByIdMembers400Error";
import type { GetV1TeamsByIdMembers400Meta } from "./getV1TeamsByIdMembers400Meta";

export type GetV1TeamsByIdMembers400 = {
  success: false;
  error: GetV1TeamsByIdMembers400Error;
  meta: GetV1TeamsByIdMembers400Meta;
};
