/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

## Quick start

Use the `/v2` routes for the current stable surface.

## Request notes

- All API endpoints have a global rate limit of 7 requests per second per IP.
- Include a valid `Origin` header such as `https://suicaodex.com` or `https://moetruyen.net` when making browser-like requests.

## Versioning

- From 01/04/2026, v1 routes are deprecated, pleade use v2 instead.

## Repositories

- API repo: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api)
- Original site repo: [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)
 * OpenAPI spec version: 0.2.0
 */

export type PostV2ChaptersByIdPageAccess200DataPagesItemGrant = {
  version: 1;
  algorithm: "IMGX-GRANT-WRAP-v1";
  codecVersions: [2, 3];
  defaultCodecVersion: 3;
  contentAlgorithm: "IMGX-AES-256-GCM-HKDF-v3";
  legacyAlgorithm: "IMGX-HMAC-SHA256-v2";
  /** @minLength 1 */
  imageId: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  issuedAt: number;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  expiresAt: number;
  /** @minLength 1 */
  nonce: string;
  /** @minLength 1 */
  keyNonce: string;
  /** @minLength 1 */
  keyHash: string;
  /** @minLength 1 */
  contentKeyHash: string;
  /** @minLength 1 */
  signature: string;
  /** @minLength 1 */
  wrappedDecodeKey: string;
  /** @minLength 1 */
  wrappedContentKey: string;
};
