/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ControllersCreateMangaRelationRequest,
  ControllersCreateMangaRequest,
  ControllersDeleteMangaRelationRequest,
  ControllersUpdateMangaRequest,
  GetMangaDraftParams,
  GetMangaParams,
  GetMangaRandomParams,
  GetMangaTopParams,
  Manga,
  MangaFeedResponse,
  Relation,
} from "../../model";

/**
 * @summary Search Manga
 */
export type getMangaResponse200 = {
  data: MangaFeedResponse;
  status: 200;
};

export type getMangaResponse400 = {
  data: void;
  status: 400;
};

export type getMangaResponse500 = {
  data: void;
  status: 500;
};

export type getMangaResponseSuccess = getMangaResponse200 & {
  headers: Headers;
};
export type getMangaResponseError = (
  | getMangaResponse400
  | getMangaResponse500
) & {
  headers: Headers;
};

export type getMangaResponse = getMangaResponseSuccess | getMangaResponseError;

export const getGetMangaUrl = (params?: GetMangaParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/manga?${stringifiedParams}`
    : `https://wd.memaydex.online/manga`;
};

export const getManga = async (
  params?: GetMangaParams,
  options?: RequestInit,
): Promise<getMangaResponse> => {
  const res = await fetch(getGetMangaUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMangaResponse;
};

export const getGetMangaQueryKey = (params?: GetMangaParams) => {
  return [
    `https://wd.memaydex.online/manga`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaQueryOptions = <
  TData = Awaited<ReturnType<typeof getManga>>,
  TError = void,
>(
  params?: GetMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getManga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getManga>>> = ({
    signal,
  }) => getManga(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getManga>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getManga>>
>;
export type GetMangaQueryError = void;

export function useGetManga<
  TData = Awaited<ReturnType<typeof getManga>>,
  TError = void,
>(
  params: undefined | GetMangaParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getManga>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManga>>,
          TError,
          Awaited<ReturnType<typeof getManga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManga<
  TData = Awaited<ReturnType<typeof getManga>>,
  TError = void,
>(
  params?: GetMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getManga>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManga>>,
          TError,
          Awaited<ReturnType<typeof getManga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetManga<
  TData = Awaited<ReturnType<typeof getManga>>,
  TError = void,
>(
  params?: GetMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getManga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Manga
 */

export function useGetManga<
  TData = Awaited<ReturnType<typeof getManga>>,
  TError = void,
>(
  params?: GetMangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getManga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create Manga
 */
export type postMangaResponse200 = {
  data: Manga;
  status: 200;
};

export type postMangaResponse400 = {
  data: void;
  status: 400;
};

export type postMangaResponse403 = {
  data: void;
  status: 403;
};

export type postMangaResponse500 = {
  data: void;
  status: 500;
};

export type postMangaResponseSuccess = postMangaResponse200 & {
  headers: Headers;
};
export type postMangaResponseError = (
  | postMangaResponse400
  | postMangaResponse403
  | postMangaResponse500
) & {
  headers: Headers;
};

export type postMangaResponse =
  | postMangaResponseSuccess
  | postMangaResponseError;

export const getPostMangaUrl = () => {
  return `https://wd.memaydex.online/manga`;
};

export const postManga = async (
  controllersCreateMangaRequest: ControllersCreateMangaRequest,
  options?: RequestInit,
): Promise<postMangaResponse> => {
  const res = await fetch(getPostMangaUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersCreateMangaRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMangaResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postMangaResponse;
};

export const getPostMangaMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postManga>>,
    TError,
    { data: ControllersCreateMangaRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postManga>>,
  TError,
  { data: ControllersCreateMangaRequest },
  TContext
> => {
  const mutationKey = ["postManga"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postManga>>,
    { data: ControllersCreateMangaRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postManga(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMangaMutationResult = NonNullable<
  Awaited<ReturnType<typeof postManga>>
>;
export type PostMangaMutationBody = ControllersCreateMangaRequest;
export type PostMangaMutationError = void;

/**
 * @summary Create Manga
 */
export const usePostManga = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postManga>>,
      TError,
      { data: ControllersCreateMangaRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postManga>>,
  TError,
  { data: ControllersCreateMangaRequest },
  TContext
> => {
  return useMutation(getPostMangaMutationOptions(options), queryClient);
};
/**
 * @summary Get Manga Relations
 */
export type getMangaIdRelationsResponse200 = {
  data: Relation[];
  status: 200;
};

export type getMangaIdRelationsResponse400 = {
  data: void;
  status: 400;
};

export type getMangaIdRelationsResponse404 = {
  data: void;
  status: 404;
};

export type getMangaIdRelationsResponse500 = {
  data: void;
  status: 500;
};

export type getMangaIdRelationsResponseSuccess =
  getMangaIdRelationsResponse200 & {
    headers: Headers;
  };
export type getMangaIdRelationsResponseError = (
  | getMangaIdRelationsResponse400
  | getMangaIdRelationsResponse404
  | getMangaIdRelationsResponse500
) & {
  headers: Headers;
};

export type getMangaIdRelationsResponse =
  | getMangaIdRelationsResponseSuccess
  | getMangaIdRelationsResponseError;

export const getGetMangaIdRelationsUrl = () => {
  return `https://wd.memaydex.online/manga/:id/relations`;
};

export const getMangaIdRelations = async (
  options?: RequestInit,
): Promise<getMangaIdRelationsResponse> => {
  const res = await fetch(getGetMangaIdRelationsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaIdRelationsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaIdRelationsResponse;
};

export const getGetMangaIdRelationsQueryKey = () => {
  return [`https://wd.memaydex.online/manga/:id/relations`] as const;
};

export const getGetMangaIdRelationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaIdRelations>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMangaIdRelations>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaIdRelationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMangaIdRelations>>
  > = ({ signal }) => getMangaIdRelations({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaIdRelations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaIdRelationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaIdRelations>>
>;
export type GetMangaIdRelationsQueryError = void;

export function useGetMangaIdRelations<
  TData = Awaited<ReturnType<typeof getMangaIdRelations>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRelations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdRelations>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdRelations>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdRelations<
  TData = Awaited<ReturnType<typeof getMangaIdRelations>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRelations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdRelations>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdRelations>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdRelations<
  TData = Awaited<ReturnType<typeof getMangaIdRelations>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRelations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Manga Relations
 */

export function useGetMangaIdRelations<
  TData = Awaited<ReturnType<typeof getMangaIdRelations>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRelations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaIdRelationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create Manga Relation
 */
export type postMangaIdRelationsResponse200 = {
  data: Relation;
  status: 200;
};

export type postMangaIdRelationsResponse400 = {
  data: void;
  status: 400;
};

export type postMangaIdRelationsResponse403 = {
  data: void;
  status: 403;
};

export type postMangaIdRelationsResponse404 = {
  data: void;
  status: 404;
};

export type postMangaIdRelationsResponse500 = {
  data: void;
  status: 500;
};

export type postMangaIdRelationsResponseSuccess =
  postMangaIdRelationsResponse200 & {
    headers: Headers;
  };
export type postMangaIdRelationsResponseError = (
  | postMangaIdRelationsResponse400
  | postMangaIdRelationsResponse403
  | postMangaIdRelationsResponse404
  | postMangaIdRelationsResponse500
) & {
  headers: Headers;
};

export type postMangaIdRelationsResponse =
  | postMangaIdRelationsResponseSuccess
  | postMangaIdRelationsResponseError;

export const getPostMangaIdRelationsUrl = () => {
  return `https://wd.memaydex.online/manga/:id/relations`;
};

export const postMangaIdRelations = async (
  controllersCreateMangaRelationRequest: ControllersCreateMangaRelationRequest,
  options?: RequestInit,
): Promise<postMangaIdRelationsResponse> => {
  const res = await fetch(getPostMangaIdRelationsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersCreateMangaRelationRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMangaIdRelationsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postMangaIdRelationsResponse;
};

export const getPostMangaIdRelationsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMangaIdRelations>>,
    TError,
    { data: ControllersCreateMangaRelationRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMangaIdRelations>>,
  TError,
  { data: ControllersCreateMangaRelationRequest },
  TContext
> => {
  const mutationKey = ["postMangaIdRelations"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMangaIdRelations>>,
    { data: ControllersCreateMangaRelationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postMangaIdRelations(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMangaIdRelationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMangaIdRelations>>
>;
export type PostMangaIdRelationsMutationBody =
  ControllersCreateMangaRelationRequest;
export type PostMangaIdRelationsMutationError = void;

/**
 * @summary Create Manga Relation
 */
export const usePostMangaIdRelations = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMangaIdRelations>>,
      TError,
      { data: ControllersCreateMangaRelationRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMangaIdRelations>>,
  TError,
  { data: ControllersCreateMangaRelationRequest },
  TContext
> => {
  return useMutation(
    getPostMangaIdRelationsMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Delete Manga Relation
 */
export type deleteMangaIdRelationsResponse204 = {
  data: void;
  status: 204;
};

export type deleteMangaIdRelationsResponse400 = {
  data: void;
  status: 400;
};

export type deleteMangaIdRelationsResponse403 = {
  data: void;
  status: 403;
};

export type deleteMangaIdRelationsResponse404 = {
  data: void;
  status: 404;
};

export type deleteMangaIdRelationsResponse500 = {
  data: void;
  status: 500;
};

export type deleteMangaIdRelationsResponseSuccess =
  deleteMangaIdRelationsResponse204 & {
    headers: Headers;
  };
export type deleteMangaIdRelationsResponseError = (
  | deleteMangaIdRelationsResponse400
  | deleteMangaIdRelationsResponse403
  | deleteMangaIdRelationsResponse404
  | deleteMangaIdRelationsResponse500
) & {
  headers: Headers;
};

export type deleteMangaIdRelationsResponse =
  | deleteMangaIdRelationsResponseSuccess
  | deleteMangaIdRelationsResponseError;

export const getDeleteMangaIdRelationsUrl = () => {
  return `https://wd.memaydex.online/manga/:id/relations`;
};

export const deleteMangaIdRelations = async (
  controllersDeleteMangaRelationRequest: ControllersDeleteMangaRelationRequest,
  options?: RequestInit,
): Promise<deleteMangaIdRelationsResponse> => {
  const res = await fetch(getDeleteMangaIdRelationsUrl(), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersDeleteMangaRelationRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMangaIdRelationsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteMangaIdRelationsResponse;
};

export const getDeleteMangaIdRelationsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMangaIdRelations>>,
    TError,
    { data: ControllersDeleteMangaRelationRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMangaIdRelations>>,
  TError,
  { data: ControllersDeleteMangaRelationRequest },
  TContext
> => {
  const mutationKey = ["deleteMangaIdRelations"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMangaIdRelations>>,
    { data: ControllersDeleteMangaRelationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteMangaIdRelations(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMangaIdRelationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMangaIdRelations>>
>;
export type DeleteMangaIdRelationsMutationBody =
  ControllersDeleteMangaRelationRequest;
export type DeleteMangaIdRelationsMutationError = void;

/**
 * @summary Delete Manga Relation
 */
export const useDeleteMangaIdRelations = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMangaIdRelations>>,
      TError,
      { data: ControllersDeleteMangaRelationRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMangaIdRelations>>,
  TError,
  { data: ControllersDeleteMangaRelationRequest },
  TContext
> => {
  return useMutation(
    getDeleteMangaIdRelationsMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Search Manga Draft
 */
export type getMangaDraftResponse200 = {
  data: MangaFeedResponse;
  status: 200;
};

export type getMangaDraftResponse400 = {
  data: void;
  status: 400;
};

export type getMangaDraftResponse403 = {
  data: void;
  status: 403;
};

export type getMangaDraftResponse500 = {
  data: void;
  status: 500;
};

export type getMangaDraftResponseSuccess = getMangaDraftResponse200 & {
  headers: Headers;
};
export type getMangaDraftResponseError = (
  | getMangaDraftResponse400
  | getMangaDraftResponse403
  | getMangaDraftResponse500
) & {
  headers: Headers;
};

export type getMangaDraftResponse =
  | getMangaDraftResponseSuccess
  | getMangaDraftResponseError;

export const getGetMangaDraftUrl = (params?: GetMangaDraftParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/manga/draft?${stringifiedParams}`
    : `https://wd.memaydex.online/manga/draft`;
};

export const getMangaDraft = async (
  params?: GetMangaDraftParams,
  options?: RequestInit,
): Promise<getMangaDraftResponse> => {
  const res = await fetch(getGetMangaDraftUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaDraftResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaDraftResponse;
};

export const getGetMangaDraftQueryKey = (params?: GetMangaDraftParams) => {
  return [
    `https://wd.memaydex.online/manga/draft`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaDraftQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaDraft>>,
  TError = void,
>(
  params?: GetMangaDraftParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaDraft>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaDraftQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaDraft>>> = ({
    signal,
  }) => getMangaDraft(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaDraft>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaDraftQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaDraft>>
>;
export type GetMangaDraftQueryError = void;

export function useGetMangaDraft<
  TData = Awaited<ReturnType<typeof getMangaDraft>>,
  TError = void,
>(
  params: undefined | GetMangaDraftParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaDraft>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaDraft>>,
          TError,
          Awaited<ReturnType<typeof getMangaDraft>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaDraft<
  TData = Awaited<ReturnType<typeof getMangaDraft>>,
  TError = void,
>(
  params?: GetMangaDraftParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaDraft>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaDraft>>,
          TError,
          Awaited<ReturnType<typeof getMangaDraft>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaDraft<
  TData = Awaited<ReturnType<typeof getMangaDraft>>,
  TError = void,
>(
  params?: GetMangaDraftParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaDraft>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Manga Draft
 */

export function useGetMangaDraft<
  TData = Awaited<ReturnType<typeof getMangaDraft>>,
  TError = void,
>(
  params?: GetMangaDraftParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaDraft>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaDraftQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Manga Draft
 */
export type getMangaDraftIdResponse200 = {
  data: Manga;
  status: 200;
};

export type getMangaDraftIdResponse400 = {
  data: void;
  status: 400;
};

export type getMangaDraftIdResponse403 = {
  data: void;
  status: 403;
};

export type getMangaDraftIdResponse404 = {
  data: void;
  status: 404;
};

export type getMangaDraftIdResponse500 = {
  data: void;
  status: 500;
};

export type getMangaDraftIdResponseSuccess = getMangaDraftIdResponse200 & {
  headers: Headers;
};
export type getMangaDraftIdResponseError = (
  | getMangaDraftIdResponse400
  | getMangaDraftIdResponse403
  | getMangaDraftIdResponse404
  | getMangaDraftIdResponse500
) & {
  headers: Headers;
};

export type getMangaDraftIdResponse =
  | getMangaDraftIdResponseSuccess
  | getMangaDraftIdResponseError;

export const getGetMangaDraftIdUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/draft/${id}`;
};

export const getMangaDraftId = async (
  id: string,
  options?: RequestInit,
): Promise<getMangaDraftIdResponse> => {
  const res = await fetch(getGetMangaDraftIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaDraftIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaDraftIdResponse;
};

export const getGetMangaDraftIdQueryKey = (id: string) => {
  return [`https://wd.memaydex.online/manga/draft/${id}`] as const;
};

export const getGetMangaDraftIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaDraftId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaDraftId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaDraftIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaDraftId>>> = ({
    signal,
  }) => getMangaDraftId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaDraftId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaDraftIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaDraftId>>
>;
export type GetMangaDraftIdQueryError = void;

export function useGetMangaDraftId<
  TData = Awaited<ReturnType<typeof getMangaDraftId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaDraftId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaDraftId>>,
          TError,
          Awaited<ReturnType<typeof getMangaDraftId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaDraftId<
  TData = Awaited<ReturnType<typeof getMangaDraftId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaDraftId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaDraftId>>,
          TError,
          Awaited<ReturnType<typeof getMangaDraftId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaDraftId<
  TData = Awaited<ReturnType<typeof getMangaDraftId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaDraftId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Manga Draft
 */

export function useGetMangaDraftId<
  TData = Awaited<ReturnType<typeof getMangaDraftId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaDraftId>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaDraftIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Submit Manga Draft
 */
export type postMangaDraftIdCommitResponse200 = {
  data: Manga;
  status: 200;
};

export type postMangaDraftIdCommitResponse400 = {
  data: void;
  status: 400;
};

export type postMangaDraftIdCommitResponse403 = {
  data: void;
  status: 403;
};

export type postMangaDraftIdCommitResponse404 = {
  data: void;
  status: 404;
};

export type postMangaDraftIdCommitResponse500 = {
  data: void;
  status: 500;
};

export type postMangaDraftIdCommitResponseSuccess =
  postMangaDraftIdCommitResponse200 & {
    headers: Headers;
  };
export type postMangaDraftIdCommitResponseError = (
  | postMangaDraftIdCommitResponse400
  | postMangaDraftIdCommitResponse403
  | postMangaDraftIdCommitResponse404
  | postMangaDraftIdCommitResponse500
) & {
  headers: Headers;
};

export type postMangaDraftIdCommitResponse =
  | postMangaDraftIdCommitResponseSuccess
  | postMangaDraftIdCommitResponseError;

export const getPostMangaDraftIdCommitUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/draft/${id}/commit`;
};

export const postMangaDraftIdCommit = async (
  id: string,
  options?: RequestInit,
): Promise<postMangaDraftIdCommitResponse> => {
  const res = await fetch(getPostMangaDraftIdCommitUrl(id), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMangaDraftIdCommitResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postMangaDraftIdCommitResponse;
};

export const getPostMangaDraftIdCommitMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMangaDraftIdCommit>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMangaDraftIdCommit>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["postMangaDraftIdCommit"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMangaDraftIdCommit>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postMangaDraftIdCommit(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMangaDraftIdCommitMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMangaDraftIdCommit>>
>;

export type PostMangaDraftIdCommitMutationError = void;

/**
 * @summary Submit Manga Draft
 */
export const usePostMangaDraftIdCommit = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMangaDraftIdCommit>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMangaDraftIdCommit>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPostMangaDraftIdCommitMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Get Random Manga
 */
export type getMangaRandomResponse200 = {
  data: Manga;
  status: 200;
};

export type getMangaRandomResponse400 = {
  data: void;
  status: 400;
};

export type getMangaRandomResponse404 = {
  data: void;
  status: 404;
};

export type getMangaRandomResponse500 = {
  data: void;
  status: 500;
};

export type getMangaRandomResponseSuccess = getMangaRandomResponse200 & {
  headers: Headers;
};
export type getMangaRandomResponseError = (
  | getMangaRandomResponse400
  | getMangaRandomResponse404
  | getMangaRandomResponse500
) & {
  headers: Headers;
};

export type getMangaRandomResponse =
  | getMangaRandomResponseSuccess
  | getMangaRandomResponseError;

export const getGetMangaRandomUrl = (params?: GetMangaRandomParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/manga/random?${stringifiedParams}`
    : `https://wd.memaydex.online/manga/random`;
};

export const getMangaRandom = async (
  params?: GetMangaRandomParams,
  options?: RequestInit,
): Promise<getMangaRandomResponse> => {
  const res = await fetch(getGetMangaRandomUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaRandomResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaRandomResponse;
};

export const getGetMangaRandomQueryKey = (params?: GetMangaRandomParams) => {
  return [
    `https://wd.memaydex.online/manga/random`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaRandomQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaRandom>>,
  TError = void,
>(
  params?: GetMangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaRandom>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaRandomQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaRandom>>> = ({
    signal,
  }) => getMangaRandom(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaRandom>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaRandomQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaRandom>>
>;
export type GetMangaRandomQueryError = void;

export function useGetMangaRandom<
  TData = Awaited<ReturnType<typeof getMangaRandom>>,
  TError = void,
>(
  params: undefined | GetMangaRandomParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaRandom>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaRandom>>,
          TError,
          Awaited<ReturnType<typeof getMangaRandom>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaRandom<
  TData = Awaited<ReturnType<typeof getMangaRandom>>,
  TError = void,
>(
  params?: GetMangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaRandom>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaRandom>>,
          TError,
          Awaited<ReturnType<typeof getMangaRandom>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaRandom<
  TData = Awaited<ReturnType<typeof getMangaRandom>>,
  TError = void,
>(
  params?: GetMangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaRandom>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Random Manga
 */

export function useGetMangaRandom<
  TData = Awaited<ReturnType<typeof getMangaRandom>>,
  TError = void,
>(
  params?: GetMangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaRandom>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaRandomQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Top Manga
 */
export type getMangaTopResponse200 = {
  data: MangaFeedResponse;
  status: 200;
};

export type getMangaTopResponse400 = {
  data: void;
  status: 400;
};

export type getMangaTopResponse500 = {
  data: void;
  status: 500;
};

export type getMangaTopResponseSuccess = getMangaTopResponse200 & {
  headers: Headers;
};
export type getMangaTopResponseError = (
  | getMangaTopResponse400
  | getMangaTopResponse500
) & {
  headers: Headers;
};

export type getMangaTopResponse =
  | getMangaTopResponseSuccess
  | getMangaTopResponseError;

export const getGetMangaTopUrl = (params?: GetMangaTopParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      if (Array.isArray(value)) {
        value.forEach((v) =>
          normalizedParams.append(key, v === null ? "null" : String(v)),
        );
      } else {
        normalizedParams.append(
          key,
          value === null ? "null" : String(value as unknown),
        );
      }
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.memaydex.online/manga/top?${stringifiedParams}`
    : `https://wd.memaydex.online/manga/top`;
};

export const getMangaTop = async (
  params?: GetMangaTopParams,
  options?: RequestInit,
): Promise<getMangaTopResponse> => {
  const res = await fetch(getGetMangaTopUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaTopResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaTopResponse;
};

export const getGetMangaTopQueryKey = (params?: GetMangaTopParams) => {
  return [
    `https://wd.memaydex.online/manga/top`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaTopQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaTop>>,
  TError = void,
>(
  params?: GetMangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaTopQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaTop>>> = ({
    signal,
  }) => getMangaTop(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaTop>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaTopQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaTop>>
>;
export type GetMangaTopQueryError = void;

export function useGetMangaTop<
  TData = Awaited<ReturnType<typeof getMangaTop>>,
  TError = void,
>(
  params: undefined | GetMangaTopParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTop>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaTop>>,
          TError,
          Awaited<ReturnType<typeof getMangaTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaTop<
  TData = Awaited<ReturnType<typeof getMangaTop>>,
  TError = void,
>(
  params?: GetMangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTop>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaTop>>,
          TError,
          Awaited<ReturnType<typeof getMangaTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaTop<
  TData = Awaited<ReturnType<typeof getMangaTop>>,
  TError = void,
>(
  params?: GetMangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Top Manga
 */

export function useGetMangaTop<
  TData = Awaited<ReturnType<typeof getMangaTop>>,
  TError = void,
>(
  params?: GetMangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaTopQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Manga
 */
export type getMangaIdResponse200 = {
  data: Manga;
  status: 200;
};

export type getMangaIdResponse400 = {
  data: void;
  status: 400;
};

export type getMangaIdResponse404 = {
  data: void;
  status: 404;
};

export type getMangaIdResponse500 = {
  data: void;
  status: 500;
};

export type getMangaIdResponseSuccess = getMangaIdResponse200 & {
  headers: Headers;
};
export type getMangaIdResponseError = (
  | getMangaIdResponse400
  | getMangaIdResponse404
  | getMangaIdResponse500
) & {
  headers: Headers;
};

export type getMangaIdResponse =
  | getMangaIdResponseSuccess
  | getMangaIdResponseError;

export const getGetMangaIdUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/${id}`;
};

export const getMangaId = async (
  id: string,
  options?: RequestInit,
): Promise<getMangaIdResponse> => {
  const res = await fetch(getGetMangaIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaIdResponse;
};

export const getGetMangaIdQueryKey = (id: string) => {
  return [`https://wd.memaydex.online/manga/${id}`] as const;
};

export const getGetMangaIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaId>>> = ({
    signal,
  }) => getMangaId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaId>>
>;
export type GetMangaIdQueryError = void;

export function useGetMangaId<
  TData = Awaited<ReturnType<typeof getMangaId>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaId>>,
          TError,
          Awaited<ReturnType<typeof getMangaId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaId<
  TData = Awaited<ReturnType<typeof getMangaId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaId>>,
          TError,
          Awaited<ReturnType<typeof getMangaId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaId<
  TData = Awaited<ReturnType<typeof getMangaId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Manga
 */

export function useGetMangaId<
  TData = Awaited<ReturnType<typeof getMangaId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update Manga
 */
export type putMangaIdResponse200 = {
  data: Manga;
  status: 200;
};

export type putMangaIdResponse400 = {
  data: void;
  status: 400;
};

export type putMangaIdResponse403 = {
  data: void;
  status: 403;
};

export type putMangaIdResponse404 = {
  data: void;
  status: 404;
};

export type putMangaIdResponse409 = {
  data: void;
  status: 409;
};

export type putMangaIdResponse500 = {
  data: void;
  status: 500;
};

export type putMangaIdResponseSuccess = putMangaIdResponse200 & {
  headers: Headers;
};
export type putMangaIdResponseError = (
  | putMangaIdResponse400
  | putMangaIdResponse403
  | putMangaIdResponse404
  | putMangaIdResponse409
  | putMangaIdResponse500
) & {
  headers: Headers;
};

export type putMangaIdResponse =
  | putMangaIdResponseSuccess
  | putMangaIdResponseError;

export const getPutMangaIdUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/${id}`;
};

export const putMangaId = async (
  id: string,
  controllersUpdateMangaRequest: ControllersUpdateMangaRequest,
  options?: RequestInit,
): Promise<putMangaIdResponse> => {
  const res = await fetch(getPutMangaIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(controllersUpdateMangaRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putMangaIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putMangaIdResponse;
};

export const getPutMangaIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putMangaId>>,
    TError,
    { id: string; data: ControllersUpdateMangaRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putMangaId>>,
  TError,
  { id: string; data: ControllersUpdateMangaRequest },
  TContext
> => {
  const mutationKey = ["putMangaId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putMangaId>>,
    { id: string; data: ControllersUpdateMangaRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putMangaId(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutMangaIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putMangaId>>
>;
export type PutMangaIdMutationBody = ControllersUpdateMangaRequest;
export type PutMangaIdMutationError = void;

/**
 * @summary Update Manga
 */
export const usePutMangaId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putMangaId>>,
      TError,
      { id: string; data: ControllersUpdateMangaRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putMangaId>>,
  TError,
  { id: string; data: ControllersUpdateMangaRequest },
  TContext
> => {
  return useMutation(getPutMangaIdMutationOptions(options), queryClient);
};
/**
 * @summary Delete Manga
 */
export type deleteMangaIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteMangaIdResponse400 = {
  data: void;
  status: 400;
};

export type deleteMangaIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteMangaIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteMangaIdResponse500 = {
  data: void;
  status: 500;
};

export type deleteMangaIdResponseSuccess = deleteMangaIdResponse204 & {
  headers: Headers;
};
export type deleteMangaIdResponseError = (
  | deleteMangaIdResponse400
  | deleteMangaIdResponse403
  | deleteMangaIdResponse404
  | deleteMangaIdResponse500
) & {
  headers: Headers;
};

export type deleteMangaIdResponse =
  | deleteMangaIdResponseSuccess
  | deleteMangaIdResponseError;

export const getDeleteMangaIdUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/${id}`;
};

export const deleteMangaId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteMangaIdResponse> => {
  const res = await fetch(getDeleteMangaIdUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMangaIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteMangaIdResponse;
};

export const getDeleteMangaIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMangaId>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMangaId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteMangaId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMangaId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteMangaId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMangaIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMangaId>>
>;

export type DeleteMangaIdMutationError = void;

/**
 * @summary Delete Manga
 */
export const useDeleteMangaId = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMangaId>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMangaId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteMangaIdMutationOptions(options), queryClient);
};
/**
 * @summary Get Recommendations
 */
export type getMangaIdRecommendationsResponse200 = {
  data: MangaFeedResponse;
  status: 200;
};

export type getMangaIdRecommendationsResponse400 = {
  data: void;
  status: 400;
};

export type getMangaIdRecommendationsResponse404 = {
  data: void;
  status: 404;
};

export type getMangaIdRecommendationsResponse500 = {
  data: void;
  status: 500;
};

export type getMangaIdRecommendationsResponseSuccess =
  getMangaIdRecommendationsResponse200 & {
    headers: Headers;
  };
export type getMangaIdRecommendationsResponseError = (
  | getMangaIdRecommendationsResponse400
  | getMangaIdRecommendationsResponse404
  | getMangaIdRecommendationsResponse500
) & {
  headers: Headers;
};

export type getMangaIdRecommendationsResponse =
  | getMangaIdRecommendationsResponseSuccess
  | getMangaIdRecommendationsResponseError;

export const getGetMangaIdRecommendationsUrl = (id: string) => {
  return `https://wd.memaydex.online/manga/${id}/recommendations`;
};

export const getMangaIdRecommendations = async (
  id: string,
  options?: RequestInit,
): Promise<getMangaIdRecommendationsResponse> => {
  const res = await fetch(getGetMangaIdRecommendationsUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaIdRecommendationsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaIdRecommendationsResponse;
};

export const getGetMangaIdRecommendationsQueryKey = (id: string) => {
  return [`https://wd.memaydex.online/manga/${id}/recommendations`] as const;
};

export const getGetMangaIdRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaIdRecommendations>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRecommendations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMangaIdRecommendationsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMangaIdRecommendations>>
  > = ({ signal }) =>
    getMangaIdRecommendations(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaIdRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaIdRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaIdRecommendations>>
>;
export type GetMangaIdRecommendationsQueryError = void;

export function useGetMangaIdRecommendations<
  TData = Awaited<ReturnType<typeof getMangaIdRecommendations>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdRecommendations>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdRecommendations<
  TData = Awaited<ReturnType<typeof getMangaIdRecommendations>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdRecommendations>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdRecommendations<
  TData = Awaited<ReturnType<typeof getMangaIdRecommendations>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRecommendations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recommendations
 */

export function useGetMangaIdRecommendations<
  TData = Awaited<ReturnType<typeof getMangaIdRecommendations>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdRecommendations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaIdRecommendationsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
