/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

## Quick start

Use the `/v2` routes for the current stable surface.

## Request notes

- All API endpoints have a global rate limit of 7 requests per second per IP.
- Include a valid `Origin` header such as `https://suicaodex.com` or `https://moetruyen.net` when making browser-like requests.

## Versioning

- From 01/04/2026, v1 routes are deprecated, pleade use v2 instead.

## Repositories

- API repo: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api)
- Original site repo: [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)
 * OpenAPI spec version: 0.2.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetV2Genres200 } from "../../model";

/**
 * Returns public genres with visible manga counts.
 * @summary List public genres (v2)
 */
export type getV2GenresResponse200 = {
  data: GetV2Genres200;
  status: 200;
};

export type getV2GenresResponseSuccess = getV2GenresResponse200 & {
  headers: Headers;
};
export type getV2GenresResponse = getV2GenresResponseSuccess;

export const getGetV2GenresUrl = () => {
  return `https://moe.suicaodex.com/v2/genres`;
};

export const getV2Genres = async (
  options?: RequestInit,
): Promise<getV2GenresResponse> => {
  const res = await fetch(getGetV2GenresUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV2GenresResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV2GenresResponse;
};

export const getGetV2GenresQueryKey = () => {
  return [`https://moe.suicaodex.com/v2/genres`] as const;
};

export const getGetV2GenresQueryOptions = <
  TData = Awaited<ReturnType<typeof getV2Genres>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getV2Genres>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV2GenresQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV2Genres>>> = ({
    signal,
  }) => getV2Genres({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV2Genres>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV2GenresQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV2Genres>>
>;
export type GetV2GenresQueryError = unknown;

export function useGetV2Genres<
  TData = Awaited<ReturnType<typeof getV2Genres>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV2Genres>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV2Genres>>,
          TError,
          Awaited<ReturnType<typeof getV2Genres>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV2Genres<
  TData = Awaited<ReturnType<typeof getV2Genres>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV2Genres>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV2Genres>>,
          TError,
          Awaited<ReturnType<typeof getV2Genres>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV2Genres<
  TData = Awaited<ReturnType<typeof getV2Genres>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV2Genres>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List public genres (v2)
 */

export function useGetV2Genres<
  TData = Awaited<ReturnType<typeof getV2Genres>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV2Genres>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV2GenresQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
