/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ControllersCreateReplyRequest,
  ControllersUpdateReplyRequest,
  GetThreadIdRepliesParams,
  Reply,
  ReplyFeedResponse,
  Thread
} from '../../model';





/**
 * @summary Get Thread
 */
export type getThreadIdResponse200 = {
  data: Thread
  status: 200
}

export type getThreadIdResponse400 = {
  data: void
  status: 400
}

export type getThreadIdResponse404 = {
  data: void
  status: 404
}

export type getThreadIdResponse500 = {
  data: void
  status: 500
}

export type getThreadIdResponseSuccess = (getThreadIdResponse200) & {
  headers: Headers;
};
export type getThreadIdResponseError = (getThreadIdResponse400 | getThreadIdResponse404 | getThreadIdResponse500) & {
  headers: Headers;
};

export type getThreadIdResponse = (getThreadIdResponseSuccess | getThreadIdResponseError)

export const getGetThreadIdUrl = (id: string,) => {


  

  return `https://wd.memaydex.online/thread/${id}`
}

export const getThreadId = async (id: string, options?: RequestInit): Promise<getThreadIdResponse> => {
  
  const res = await fetch(getGetThreadIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThreadIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThreadIdResponse
}
  




export const getGetThreadIdQueryKey = (id: string,) => {
    return [
    `https://wd.memaydex.online/thread/${id}`
    ] as const;
    }

    
export const getGetThreadIdQueryOptions = <TData = Awaited<ReturnType<typeof getThreadId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThreadIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThreadId>>> = ({ signal }) => getThreadId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThreadIdQueryResult = NonNullable<Awaited<ReturnType<typeof getThreadId>>>
export type GetThreadIdQueryError = void


export function useGetThreadId<TData = Awaited<ReturnType<typeof getThreadId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadId>>,
          TError,
          Awaited<ReturnType<typeof getThreadId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadId<TData = Awaited<ReturnType<typeof getThreadId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadId>>,
          TError,
          Awaited<ReturnType<typeof getThreadId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadId<TData = Awaited<ReturnType<typeof getThreadId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Thread
 */

export function useGetThreadId<TData = Awaited<ReturnType<typeof getThreadId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThreadIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Replies
 */
export type getThreadIdRepliesResponse200 = {
  data: ReplyFeedResponse
  status: 200
}

export type getThreadIdRepliesResponse400 = {
  data: void
  status: 400
}

export type getThreadIdRepliesResponse404 = {
  data: void
  status: 404
}

export type getThreadIdRepliesResponse500 = {
  data: void
  status: 500
}

export type getThreadIdRepliesResponseSuccess = (getThreadIdRepliesResponse200) & {
  headers: Headers;
};
export type getThreadIdRepliesResponseError = (getThreadIdRepliesResponse400 | getThreadIdRepliesResponse404 | getThreadIdRepliesResponse500) & {
  headers: Headers;
};

export type getThreadIdRepliesResponse = (getThreadIdRepliesResponseSuccess | getThreadIdRepliesResponseError)

export const getGetThreadIdRepliesUrl = (id: string,
    params?: GetThreadIdRepliesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/thread/${id}/replies?${stringifiedParams}` : `https://wd.memaydex.online/thread/${id}/replies`
}

export const getThreadIdReplies = async (id: string,
    params?: GetThreadIdRepliesParams, options?: RequestInit): Promise<getThreadIdRepliesResponse> => {
  
  const res = await fetch(getGetThreadIdRepliesUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThreadIdRepliesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThreadIdRepliesResponse
}
  




export const getGetThreadIdRepliesQueryKey = (id: string,
    params?: GetThreadIdRepliesParams,) => {
    return [
    `https://wd.memaydex.online/thread/${id}/replies`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetThreadIdRepliesQueryOptions = <TData = Awaited<ReturnType<typeof getThreadIdReplies>>, TError = void>(id: string,
    params?: GetThreadIdRepliesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetThreadIdRepliesQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getThreadIdReplies>>> = ({ signal }) => getThreadIdReplies(id,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetThreadIdRepliesQueryResult = NonNullable<Awaited<ReturnType<typeof getThreadIdReplies>>>
export type GetThreadIdRepliesQueryError = void


export function useGetThreadIdReplies<TData = Awaited<ReturnType<typeof getThreadIdReplies>>, TError = void>(
 id: string,
    params: undefined |  GetThreadIdRepliesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadIdReplies>>,
          TError,
          Awaited<ReturnType<typeof getThreadIdReplies>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadIdReplies<TData = Awaited<ReturnType<typeof getThreadIdReplies>>, TError = void>(
 id: string,
    params?: GetThreadIdRepliesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getThreadIdReplies>>,
          TError,
          Awaited<ReturnType<typeof getThreadIdReplies>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetThreadIdReplies<TData = Awaited<ReturnType<typeof getThreadIdReplies>>, TError = void>(
 id: string,
    params?: GetThreadIdRepliesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Replies
 */

export function useGetThreadIdReplies<TData = Awaited<ReturnType<typeof getThreadIdReplies>>, TError = void>(
 id: string,
    params?: GetThreadIdRepliesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getThreadIdReplies>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetThreadIdRepliesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Reply
 */
export type postThreadIdRepliesResponse201 = {
  data: Reply
  status: 201
}

export type postThreadIdRepliesResponse400 = {
  data: void
  status: 400
}

export type postThreadIdRepliesResponse403 = {
  data: void
  status: 403
}

export type postThreadIdRepliesResponse404 = {
  data: void
  status: 404
}

export type postThreadIdRepliesResponse500 = {
  data: void
  status: 500
}

export type postThreadIdRepliesResponseSuccess = (postThreadIdRepliesResponse201) & {
  headers: Headers;
};
export type postThreadIdRepliesResponseError = (postThreadIdRepliesResponse400 | postThreadIdRepliesResponse403 | postThreadIdRepliesResponse404 | postThreadIdRepliesResponse500) & {
  headers: Headers;
};

export type postThreadIdRepliesResponse = (postThreadIdRepliesResponseSuccess | postThreadIdRepliesResponseError)

export const getPostThreadIdRepliesUrl = (id: string,) => {


  

  return `https://wd.memaydex.online/thread/${id}/replies`
}

export const postThreadIdReplies = async (id: string,
    controllersCreateReplyRequest: ControllersCreateReplyRequest, options?: RequestInit): Promise<postThreadIdRepliesResponse> => {
  
  const res = await fetch(getPostThreadIdRepliesUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      controllersCreateReplyRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postThreadIdRepliesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postThreadIdRepliesResponse
}
  



export const getPostThreadIdRepliesMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThreadIdReplies>>, TError,{id: string;data: ControllersCreateReplyRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postThreadIdReplies>>, TError,{id: string;data: ControllersCreateReplyRequest}, TContext> => {

const mutationKey = ['postThreadIdReplies'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postThreadIdReplies>>, {id: string;data: ControllersCreateReplyRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postThreadIdReplies(id,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostThreadIdRepliesMutationResult = NonNullable<Awaited<ReturnType<typeof postThreadIdReplies>>>
    export type PostThreadIdRepliesMutationBody = ControllersCreateReplyRequest
    export type PostThreadIdRepliesMutationError = void

    /**
 * @summary Create Reply
 */
export const usePostThreadIdReplies = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThreadIdReplies>>, TError,{id: string;data: ControllersCreateReplyRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postThreadIdReplies>>,
        TError,
        {id: string;data: ControllersCreateReplyRequest},
        TContext
      > => {
      return useMutation(getPostThreadIdRepliesMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Reply
 */
export type postThreadIdRepliesReplyIdResponse200 = {
  data: Reply
  status: 200
}

export type postThreadIdRepliesReplyIdResponse400 = {
  data: void
  status: 400
}

export type postThreadIdRepliesReplyIdResponse403 = {
  data: void
  status: 403
}

export type postThreadIdRepliesReplyIdResponse404 = {
  data: void
  status: 404
}

export type postThreadIdRepliesReplyIdResponse500 = {
  data: void
  status: 500
}

export type postThreadIdRepliesReplyIdResponseSuccess = (postThreadIdRepliesReplyIdResponse200) & {
  headers: Headers;
};
export type postThreadIdRepliesReplyIdResponseError = (postThreadIdRepliesReplyIdResponse400 | postThreadIdRepliesReplyIdResponse403 | postThreadIdRepliesReplyIdResponse404 | postThreadIdRepliesReplyIdResponse500) & {
  headers: Headers;
};

export type postThreadIdRepliesReplyIdResponse = (postThreadIdRepliesReplyIdResponseSuccess | postThreadIdRepliesReplyIdResponseError)

export const getPostThreadIdRepliesReplyIdUrl = (id: string,
    replyId: string,) => {


  

  return `https://wd.memaydex.online/thread/${id}/replies/${replyId}`
}

export const postThreadIdRepliesReplyId = async (id: string,
    replyId: string,
    controllersUpdateReplyRequest: ControllersUpdateReplyRequest, options?: RequestInit): Promise<postThreadIdRepliesReplyIdResponse> => {
  
  const res = await fetch(getPostThreadIdRepliesReplyIdUrl(id,replyId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      controllersUpdateReplyRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postThreadIdRepliesReplyIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postThreadIdRepliesReplyIdResponse
}
  



export const getPostThreadIdRepliesReplyIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>, TError,{id: string;replyId: string;data: ControllersUpdateReplyRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>, TError,{id: string;replyId: string;data: ControllersUpdateReplyRequest}, TContext> => {

const mutationKey = ['postThreadIdRepliesReplyId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>, {id: string;replyId: string;data: ControllersUpdateReplyRequest}> = (props) => {
          const {id,replyId,data} = props ?? {};

          return  postThreadIdRepliesReplyId(id,replyId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostThreadIdRepliesReplyIdMutationResult = NonNullable<Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>>
    export type PostThreadIdRepliesReplyIdMutationBody = ControllersUpdateReplyRequest
    export type PostThreadIdRepliesReplyIdMutationError = void

    /**
 * @summary Update Reply
 */
export const usePostThreadIdRepliesReplyId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>, TError,{id: string;replyId: string;data: ControllersUpdateReplyRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postThreadIdRepliesReplyId>>,
        TError,
        {id: string;replyId: string;data: ControllersUpdateReplyRequest},
        TContext
      > => {
      return useMutation(getPostThreadIdRepliesReplyIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Reply
 */
export type deleteThreadIdRepliesReplyIdResponse204 = {
  data: void
  status: 204
}

export type deleteThreadIdRepliesReplyIdResponse400 = {
  data: void
  status: 400
}

export type deleteThreadIdRepliesReplyIdResponse403 = {
  data: void
  status: 403
}

export type deleteThreadIdRepliesReplyIdResponse404 = {
  data: void
  status: 404
}

export type deleteThreadIdRepliesReplyIdResponse500 = {
  data: void
  status: 500
}

export type deleteThreadIdRepliesReplyIdResponseSuccess = (deleteThreadIdRepliesReplyIdResponse204) & {
  headers: Headers;
};
export type deleteThreadIdRepliesReplyIdResponseError = (deleteThreadIdRepliesReplyIdResponse400 | deleteThreadIdRepliesReplyIdResponse403 | deleteThreadIdRepliesReplyIdResponse404 | deleteThreadIdRepliesReplyIdResponse500) & {
  headers: Headers;
};

export type deleteThreadIdRepliesReplyIdResponse = (deleteThreadIdRepliesReplyIdResponseSuccess | deleteThreadIdRepliesReplyIdResponseError)

export const getDeleteThreadIdRepliesReplyIdUrl = (id: string,
    replyId: string,) => {


  

  return `https://wd.memaydex.online/thread/${id}/replies/${replyId}`
}

export const deleteThreadIdRepliesReplyId = async (id: string,
    replyId: string, options?: RequestInit): Promise<deleteThreadIdRepliesReplyIdResponse> => {
  
  const res = await fetch(getDeleteThreadIdRepliesReplyIdUrl(id,replyId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteThreadIdRepliesReplyIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteThreadIdRepliesReplyIdResponse
}
  



export const getDeleteThreadIdRepliesReplyIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>, TError,{id: string;replyId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>, TError,{id: string;replyId: string}, TContext> => {

const mutationKey = ['deleteThreadIdRepliesReplyId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>, {id: string;replyId: string}> = (props) => {
          const {id,replyId} = props ?? {};

          return  deleteThreadIdRepliesReplyId(id,replyId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteThreadIdRepliesReplyIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>>
    
    export type DeleteThreadIdRepliesReplyIdMutationError = void

    /**
 * @summary Remove Reply
 */
export const useDeleteThreadIdRepliesReplyId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>, TError,{id: string;replyId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteThreadIdRepliesReplyId>>,
        TError,
        {id: string;replyId: string},
        TContext
      > => {
      return useMutation(getDeleteThreadIdRepliesReplyIdMutationOptions(options), queryClient);
    }
    