/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Chapter,
  ChapterAggregateResponse,
  ChapterInternalErrorResponse,
  ChapterNotFoundErrorResponse,
  ChapterValidationErrorResponse,
  GetChapterFeedParams,
  GetChapterParams,
  GetChapterTopParams,
  GetChapterUpdatesParams,
  GetMangaIdAggregateParams,
  InternalErrorResponse,
  MangaNotFoundErrorResponse,
  MappedChapterFeedResponse,
  ValidationErrorResponse,
} from "../../model";

/**
 * @summary Search Chapters
 */
export type getChapterResponse200 = {
  data: MappedChapterFeedResponse;
  status: 200;
};

export type getChapterResponse400 = {
  data: ChapterValidationErrorResponse;
  status: 400;
};

export type getChapterResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterResponseSuccess = getChapterResponse200 & {
  headers: Headers;
};
export type getChapterResponseError = (
  | getChapterResponse400
  | getChapterResponse500
) & {
  headers: Headers;
};

export type getChapterResponse =
  | getChapterResponseSuccess
  | getChapterResponseError;

export const getGetChapterUrl = (params?: GetChapterParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/chapter?${stringifiedParams}`
    : `https://wd.suicaodex.com/chapter`;
};

export const getChapter = async (
  params?: GetChapterParams,
  options?: RequestInit,
): Promise<getChapterResponse> => {
  const res = await fetch(getGetChapterUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterResponse;
};

export const getGetChapterQueryKey = (params?: GetChapterParams) => {
  return [
    `https://wd.suicaodex.com/chapter`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetChapterQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapter>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChapterQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapter>>> = ({
    signal,
  }) => getChapter(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapter>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapter>>
>;
export type GetChapterQueryError =
  | ChapterValidationErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapter<
  TData = Awaited<ReturnType<typeof getChapter>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params: undefined | GetChapterParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapter>>,
          TError,
          Awaited<ReturnType<typeof getChapter>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapter<
  TData = Awaited<ReturnType<typeof getChapter>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapter>>,
          TError,
          Awaited<ReturnType<typeof getChapter>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapter<
  TData = Awaited<ReturnType<typeof getChapter>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Chapters
 */

export function useGetChapter<
  TData = Awaited<ReturnType<typeof getChapter>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Latest Feed
 */
export type getChapterFeedResponse200 = {
  data: MappedChapterFeedResponse;
  status: 200;
};

export type getChapterFeedResponse400 = {
  data: ChapterValidationErrorResponse;
  status: 400;
};

export type getChapterFeedResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterFeedResponseSuccess = getChapterFeedResponse200 & {
  headers: Headers;
};
export type getChapterFeedResponseError = (
  | getChapterFeedResponse400
  | getChapterFeedResponse500
) & {
  headers: Headers;
};

export type getChapterFeedResponse =
  | getChapterFeedResponseSuccess
  | getChapterFeedResponseError;

export const getGetChapterFeedUrl = (params?: GetChapterFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/chapter/feed?${stringifiedParams}`
    : `https://wd.suicaodex.com/chapter/feed`;
};

export const getChapterFeed = async (
  params?: GetChapterFeedParams,
  options?: RequestInit,
): Promise<getChapterFeedResponse> => {
  const res = await fetch(getGetChapterFeedUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterFeedResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterFeedResponse;
};

export const getGetChapterFeedQueryKey = (params?: GetChapterFeedParams) => {
  return [
    `https://wd.suicaodex.com/chapter/feed`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetChapterFeedQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterFeed>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChapterFeedQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterFeed>>> = ({
    signal,
  }) => getChapterFeed(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapterFeed>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterFeedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapterFeed>>
>;
export type GetChapterFeedQueryError =
  | ChapterValidationErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapterFeed<
  TData = Awaited<ReturnType<typeof getChapterFeed>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params: undefined | GetChapterFeedParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getChapterFeed>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterFeed<
  TData = Awaited<ReturnType<typeof getChapterFeed>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getChapterFeed>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterFeed<
  TData = Awaited<ReturnType<typeof getChapterFeed>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Latest Feed
 */

export function useGetChapterFeed<
  TData = Awaited<ReturnType<typeof getChapterFeed>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterFeedQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns only the most recent chapter of each manga. Use this endpoint if you don't want your feed to be filled with multiple chapters from the same manga.
 * @summary Get Latest Updates
 */
export type getChapterUpdatesResponse200 = {
  data: MappedChapterFeedResponse;
  status: 200;
};

export type getChapterUpdatesResponse400 = {
  data: ChapterValidationErrorResponse;
  status: 400;
};

export type getChapterUpdatesResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterUpdatesResponseSuccess = getChapterUpdatesResponse200 & {
  headers: Headers;
};
export type getChapterUpdatesResponseError = (
  | getChapterUpdatesResponse400
  | getChapterUpdatesResponse500
) & {
  headers: Headers;
};

export type getChapterUpdatesResponse =
  | getChapterUpdatesResponseSuccess
  | getChapterUpdatesResponseError;

export const getGetChapterUpdatesUrl = (params?: GetChapterUpdatesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/chapter/updates?${stringifiedParams}`
    : `https://wd.suicaodex.com/chapter/updates`;
};

export const getChapterUpdates = async (
  params?: GetChapterUpdatesParams,
  options?: RequestInit,
): Promise<getChapterUpdatesResponse> => {
  const res = await fetch(getGetChapterUpdatesUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterUpdatesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterUpdatesResponse;
};

export const getGetChapterUpdatesQueryKey = (
  params?: GetChapterUpdatesParams,
) => {
  return [
    `https://wd.suicaodex.com/chapter/updates`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetChapterUpdatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterUpdates>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterUpdatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterUpdates>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChapterUpdatesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChapterUpdates>>
  > = ({ signal }) => getChapterUpdates(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapterUpdates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterUpdatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapterUpdates>>
>;
export type GetChapterUpdatesQueryError =
  | ChapterValidationErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapterUpdates<
  TData = Awaited<ReturnType<typeof getChapterUpdates>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params: undefined | GetChapterUpdatesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterUpdates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterUpdates>>,
          TError,
          Awaited<ReturnType<typeof getChapterUpdates>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterUpdates<
  TData = Awaited<ReturnType<typeof getChapterUpdates>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterUpdatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterUpdates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterUpdates>>,
          TError,
          Awaited<ReturnType<typeof getChapterUpdates>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterUpdates<
  TData = Awaited<ReturnType<typeof getChapterUpdates>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterUpdatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterUpdates>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Latest Updates
 */

export function useGetChapterUpdates<
  TData = Awaited<ReturnType<typeof getChapterUpdates>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterUpdatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterUpdates>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterUpdatesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Fetch top chapters from the archived dataset ordered by chapter_stats.views desc. time is accepted as a compatibility no-op.
 * @summary Get Top Chapters
 */
export type getChapterTopResponse200 = {
  data: MappedChapterFeedResponse;
  status: 200;
};

export type getChapterTopResponse400 = {
  data: ChapterValidationErrorResponse;
  status: 400;
};

export type getChapterTopResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterTopResponseSuccess = getChapterTopResponse200 & {
  headers: Headers;
};
export type getChapterTopResponseError = (
  | getChapterTopResponse400
  | getChapterTopResponse500
) & {
  headers: Headers;
};

export type getChapterTopResponse =
  | getChapterTopResponseSuccess
  | getChapterTopResponseError;

export const getGetChapterTopUrl = (params?: GetChapterTopParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/chapter/top?${stringifiedParams}`
    : `https://wd.suicaodex.com/chapter/top`;
};

export const getChapterTop = async (
  params?: GetChapterTopParams,
  options?: RequestInit,
): Promise<getChapterTopResponse> => {
  const res = await fetch(getGetChapterTopUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterTopResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterTopResponse;
};

export const getGetChapterTopQueryKey = (params?: GetChapterTopParams) => {
  return [
    `https://wd.suicaodex.com/chapter/top`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetChapterTopQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterTop>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChapterTopQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterTop>>> = ({
    signal,
  }) => getChapterTop(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapterTop>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterTopQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapterTop>>
>;
export type GetChapterTopQueryError =
  | ChapterValidationErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapterTop<
  TData = Awaited<ReturnType<typeof getChapterTop>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params: undefined | GetChapterTopParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterTop>>,
          TError,
          Awaited<ReturnType<typeof getChapterTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterTop<
  TData = Awaited<ReturnType<typeof getChapterTop>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterTop>>,
          TError,
          Awaited<ReturnType<typeof getChapterTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterTop<
  TData = Awaited<ReturnType<typeof getChapterTop>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Top Chapters
 */

export function useGetChapterTop<
  TData = Awaited<ReturnType<typeof getChapterTop>>,
  TError = ChapterValidationErrorResponse | ChapterInternalErrorResponse,
>(
  params?: GetChapterTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterTopQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Chapter
 */
export type getChapterIdResponse200 = {
  data: Chapter;
  status: 200;
};

export type getChapterIdResponse404 = {
  data: ChapterNotFoundErrorResponse;
  status: 404;
};

export type getChapterIdResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterIdResponseSuccess = getChapterIdResponse200 & {
  headers: Headers;
};
export type getChapterIdResponseError = (
  | getChapterIdResponse404
  | getChapterIdResponse500
) & {
  headers: Headers;
};

export type getChapterIdResponse =
  | getChapterIdResponseSuccess
  | getChapterIdResponseError;

export const getGetChapterIdUrl = (id: string) => {
  return `https://wd.suicaodex.com/chapter/${id}`;
};

export const getChapterId = async (
  id: string,
  options?: RequestInit,
): Promise<getChapterIdResponse> => {
  const res = await fetch(getGetChapterIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterIdResponse;
};

export const getGetChapterIdQueryKey = (id: string) => {
  return [`https://wd.suicaodex.com/chapter/${id}`] as const;
};

export const getGetChapterIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterId>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChapterIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterId>>> = ({
    signal,
  }) => getChapterId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapterId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapterId>>
>;
export type GetChapterIdQueryError =
  | ChapterNotFoundErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapterId<
  TData = Awaited<ReturnType<typeof getChapterId>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterId>>,
          TError,
          Awaited<ReturnType<typeof getChapterId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterId<
  TData = Awaited<ReturnType<typeof getChapterId>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterId>>,
          TError,
          Awaited<ReturnType<typeof getChapterId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterId<
  TData = Awaited<ReturnType<typeof getChapterId>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chapter
 */

export function useGetChapterId<
  TData = Awaited<ReturnType<typeof getChapterId>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Aggregate chapter entries for a manga, grouped by chapter and volume.
 * @summary Get Aggregated Chapter List
 */
export type getMangaIdAggregateResponse200 = {
  data: ChapterAggregateResponse;
  status: 200;
};

export type getMangaIdAggregateResponse400 = {
  data: ValidationErrorResponse;
  status: 400;
};

export type getMangaIdAggregateResponse404 = {
  data: MangaNotFoundErrorResponse;
  status: 404;
};

export type getMangaIdAggregateResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getMangaIdAggregateResponseSuccess =
  getMangaIdAggregateResponse200 & {
    headers: Headers;
  };
export type getMangaIdAggregateResponseError = (
  | getMangaIdAggregateResponse400
  | getMangaIdAggregateResponse404
  | getMangaIdAggregateResponse500
) & {
  headers: Headers;
};

export type getMangaIdAggregateResponse =
  | getMangaIdAggregateResponseSuccess
  | getMangaIdAggregateResponseError;

export const getGetMangaIdAggregateUrl = (
  id: string,
  params?: GetMangaIdAggregateParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/manga/${id}/aggregate?${stringifiedParams}`
    : `https://wd.suicaodex.com/manga/${id}/aggregate`;
};

export const getMangaIdAggregate = async (
  id: string,
  params?: GetMangaIdAggregateParams,
  options?: RequestInit,
): Promise<getMangaIdAggregateResponse> => {
  const res = await fetch(getGetMangaIdAggregateUrl(id, params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaIdAggregateResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaIdAggregateResponse;
};

export const getGetMangaIdAggregateQueryKey = (
  id: string,
  params?: GetMangaIdAggregateParams,
) => {
  return [
    `https://wd.suicaodex.com/manga/${id}/aggregate`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaIdAggregateQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaIdAggregate>>,
  TError =
    | ValidationErrorResponse
    | MangaNotFoundErrorResponse
    | InternalErrorResponse,
>(
  id: string,
  params?: GetMangaIdAggregateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdAggregate>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMangaIdAggregateQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMangaIdAggregate>>
  > = ({ signal }) =>
    getMangaIdAggregate(id, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaIdAggregate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaIdAggregateQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaIdAggregate>>
>;
export type GetMangaIdAggregateQueryError =
  | ValidationErrorResponse
  | MangaNotFoundErrorResponse
  | InternalErrorResponse;

export function useGetMangaIdAggregate<
  TData = Awaited<ReturnType<typeof getMangaIdAggregate>>,
  TError =
    | ValidationErrorResponse
    | MangaNotFoundErrorResponse
    | InternalErrorResponse,
>(
  id: string,
  params: undefined | GetMangaIdAggregateParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdAggregate>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdAggregate>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdAggregate>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdAggregate<
  TData = Awaited<ReturnType<typeof getMangaIdAggregate>>,
  TError =
    | ValidationErrorResponse
    | MangaNotFoundErrorResponse
    | InternalErrorResponse,
>(
  id: string,
  params?: GetMangaIdAggregateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdAggregate>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdAggregate>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdAggregate>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdAggregate<
  TData = Awaited<ReturnType<typeof getMangaIdAggregate>>,
  TError =
    | ValidationErrorResponse
    | MangaNotFoundErrorResponse
    | InternalErrorResponse,
>(
  id: string,
  params?: GetMangaIdAggregateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdAggregate>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Aggregated Chapter List
 */

export function useGetMangaIdAggregate<
  TData = Awaited<ReturnType<typeof getMangaIdAggregate>>,
  TError =
    | ValidationErrorResponse
    | MangaNotFoundErrorResponse
    | InternalErrorResponse,
>(
  id: string,
  params?: GetMangaIdAggregateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdAggregate>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaIdAggregateQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
