/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Chapter,
  ChapterAggregateResponse,
  ChapterFeedResponse,
  ControllersUpdateChapterRequest,
  GetChapterFeedParams,
  GetChapterParams,
  GetChapterTopParams,
  GetChapterUpdatesParams,
  GetMangaIdAggregateParams,
  GetMangaIdChaptersParams,
  MappedChapterFeedResponse
} from '../../model';





/**
 * @summary Search Chapters
 */
export type getChapterResponse200 = {
  data: MappedChapterFeedResponse
  status: 200
}

export type getChapterResponse400 = {
  data: void
  status: 400
}

export type getChapterResponse500 = {
  data: void
  status: 500
}

export type getChapterResponseSuccess = (getChapterResponse200) & {
  headers: Headers;
};
export type getChapterResponseError = (getChapterResponse400 | getChapterResponse500) & {
  headers: Headers;
};

export type getChapterResponse = (getChapterResponseSuccess | getChapterResponseError)

export const getGetChapterUrl = (params?: GetChapterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/chapter?${stringifiedParams}` : `https://wd.memaydex.online/chapter`
}

export const getChapter = async (params?: GetChapterParams, options?: RequestInit): Promise<getChapterResponse> => {
  
  const res = await fetch(getGetChapterUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getChapterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChapterResponse
}
  




export const getGetChapterQueryKey = (params?: GetChapterParams,) => {
    return [
    `https://wd.memaydex.online/chapter`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetChapterQueryOptions = <TData = Awaited<ReturnType<typeof getChapter>>, TError = void>(params?: GetChapterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChapterQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapter>>> = ({ signal }) => getChapter(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChapterQueryResult = NonNullable<Awaited<ReturnType<typeof getChapter>>>
export type GetChapterQueryError = void


export function useGetChapter<TData = Awaited<ReturnType<typeof getChapter>>, TError = void>(
 params: undefined |  GetChapterParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapter>>,
          TError,
          Awaited<ReturnType<typeof getChapter>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapter<TData = Awaited<ReturnType<typeof getChapter>>, TError = void>(
 params?: GetChapterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapter>>,
          TError,
          Awaited<ReturnType<typeof getChapter>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapter<TData = Awaited<ReturnType<typeof getChapter>>, TError = void>(
 params?: GetChapterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Chapters
 */

export function useGetChapter<TData = Awaited<ReturnType<typeof getChapter>>, TError = void>(
 params?: GetChapterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapter>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChapterQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Latest Feed
 */
export type getChapterFeedResponse200 = {
  data: MappedChapterFeedResponse
  status: 200
}

export type getChapterFeedResponse400 = {
  data: void
  status: 400
}

export type getChapterFeedResponse500 = {
  data: void
  status: 500
}

export type getChapterFeedResponseSuccess = (getChapterFeedResponse200) & {
  headers: Headers;
};
export type getChapterFeedResponseError = (getChapterFeedResponse400 | getChapterFeedResponse500) & {
  headers: Headers;
};

export type getChapterFeedResponse = (getChapterFeedResponseSuccess | getChapterFeedResponseError)

export const getGetChapterFeedUrl = (params?: GetChapterFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/chapter/feed?${stringifiedParams}` : `https://wd.memaydex.online/chapter/feed`
}

export const getChapterFeed = async (params?: GetChapterFeedParams, options?: RequestInit): Promise<getChapterFeedResponse> => {
  
  const res = await fetch(getGetChapterFeedUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getChapterFeedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChapterFeedResponse
}
  




export const getGetChapterFeedQueryKey = (params?: GetChapterFeedParams,) => {
    return [
    `https://wd.memaydex.online/chapter/feed`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetChapterFeedQueryOptions = <TData = Awaited<ReturnType<typeof getChapterFeed>>, TError = void>(params?: GetChapterFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChapterFeedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterFeed>>> = ({ signal }) => getChapterFeed(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChapterFeedQueryResult = NonNullable<Awaited<ReturnType<typeof getChapterFeed>>>
export type GetChapterFeedQueryError = void


export function useGetChapterFeed<TData = Awaited<ReturnType<typeof getChapterFeed>>, TError = void>(
 params: undefined |  GetChapterFeedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getChapterFeed>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterFeed<TData = Awaited<ReturnType<typeof getChapterFeed>>, TError = void>(
 params?: GetChapterFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterFeed>>,
          TError,
          Awaited<ReturnType<typeof getChapterFeed>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterFeed<TData = Awaited<ReturnType<typeof getChapterFeed>>, TError = void>(
 params?: GetChapterFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Latest Feed
 */

export function useGetChapterFeed<TData = Awaited<ReturnType<typeof getChapterFeed>>, TError = void>(
 params?: GetChapterFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterFeed>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChapterFeedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Top Chapters
 */
export type getChapterTopResponse200 = {
  data: MappedChapterFeedResponse
  status: 200
}

export type getChapterTopResponse400 = {
  data: void
  status: 400
}

export type getChapterTopResponse500 = {
  data: void
  status: 500
}

export type getChapterTopResponseSuccess = (getChapterTopResponse200) & {
  headers: Headers;
};
export type getChapterTopResponseError = (getChapterTopResponse400 | getChapterTopResponse500) & {
  headers: Headers;
};

export type getChapterTopResponse = (getChapterTopResponseSuccess | getChapterTopResponseError)

export const getGetChapterTopUrl = (params?: GetChapterTopParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/chapter/top?${stringifiedParams}` : `https://wd.memaydex.online/chapter/top`
}

export const getChapterTop = async (params?: GetChapterTopParams, options?: RequestInit): Promise<getChapterTopResponse> => {
  
  const res = await fetch(getGetChapterTopUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getChapterTopResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChapterTopResponse
}
  




export const getGetChapterTopQueryKey = (params?: GetChapterTopParams,) => {
    return [
    `https://wd.memaydex.online/chapter/top`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetChapterTopQueryOptions = <TData = Awaited<ReturnType<typeof getChapterTop>>, TError = void>(params?: GetChapterTopParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChapterTopQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterTop>>> = ({ signal }) => getChapterTop(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChapterTopQueryResult = NonNullable<Awaited<ReturnType<typeof getChapterTop>>>
export type GetChapterTopQueryError = void


export function useGetChapterTop<TData = Awaited<ReturnType<typeof getChapterTop>>, TError = void>(
 params: undefined |  GetChapterTopParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterTop>>,
          TError,
          Awaited<ReturnType<typeof getChapterTop>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterTop<TData = Awaited<ReturnType<typeof getChapterTop>>, TError = void>(
 params?: GetChapterTopParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterTop>>,
          TError,
          Awaited<ReturnType<typeof getChapterTop>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterTop<TData = Awaited<ReturnType<typeof getChapterTop>>, TError = void>(
 params?: GetChapterTopParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Top Chapters
 */

export function useGetChapterTop<TData = Awaited<ReturnType<typeof getChapterTop>>, TError = void>(
 params?: GetChapterTopParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterTop>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChapterTopQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Returns only the most recent chapter of each manga. Use this endpoint if you don't want your feed to be filled with multiple chapters from the same manga.
 * @summary Get Latest Updates
 */
export type getChapterUpdatesResponse200 = {
  data: ChapterFeedResponse
  status: 200
}

export type getChapterUpdatesResponse400 = {
  data: void
  status: 400
}

export type getChapterUpdatesResponse500 = {
  data: void
  status: 500
}

export type getChapterUpdatesResponseSuccess = (getChapterUpdatesResponse200) & {
  headers: Headers;
};
export type getChapterUpdatesResponseError = (getChapterUpdatesResponse400 | getChapterUpdatesResponse500) & {
  headers: Headers;
};

export type getChapterUpdatesResponse = (getChapterUpdatesResponseSuccess | getChapterUpdatesResponseError)

export const getGetChapterUpdatesUrl = (params?: GetChapterUpdatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/chapter/updates?${stringifiedParams}` : `https://wd.memaydex.online/chapter/updates`
}

export const getChapterUpdates = async (params?: GetChapterUpdatesParams, options?: RequestInit): Promise<getChapterUpdatesResponse> => {
  
  const res = await fetch(getGetChapterUpdatesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getChapterUpdatesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChapterUpdatesResponse
}
  




export const getGetChapterUpdatesQueryKey = (params?: GetChapterUpdatesParams,) => {
    return [
    `https://wd.memaydex.online/chapter/updates`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetChapterUpdatesQueryOptions = <TData = Awaited<ReturnType<typeof getChapterUpdates>>, TError = void>(params?: GetChapterUpdatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChapterUpdatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterUpdates>>> = ({ signal }) => getChapterUpdates(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChapterUpdatesQueryResult = NonNullable<Awaited<ReturnType<typeof getChapterUpdates>>>
export type GetChapterUpdatesQueryError = void


export function useGetChapterUpdates<TData = Awaited<ReturnType<typeof getChapterUpdates>>, TError = void>(
 params: undefined |  GetChapterUpdatesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterUpdates>>,
          TError,
          Awaited<ReturnType<typeof getChapterUpdates>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterUpdates<TData = Awaited<ReturnType<typeof getChapterUpdates>>, TError = void>(
 params?: GetChapterUpdatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterUpdates>>,
          TError,
          Awaited<ReturnType<typeof getChapterUpdates>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterUpdates<TData = Awaited<ReturnType<typeof getChapterUpdates>>, TError = void>(
 params?: GetChapterUpdatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Latest Updates
 */

export function useGetChapterUpdates<TData = Awaited<ReturnType<typeof getChapterUpdates>>, TError = void>(
 params?: GetChapterUpdatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterUpdates>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChapterUpdatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Chapter
 */
export type getChapterIdResponse200 = {
  data: Chapter
  status: 200
}

export type getChapterIdResponse400 = {
  data: void
  status: 400
}

export type getChapterIdResponse404 = {
  data: void
  status: 404
}

export type getChapterIdResponse500 = {
  data: void
  status: 500
}

export type getChapterIdResponseSuccess = (getChapterIdResponse200) & {
  headers: Headers;
};
export type getChapterIdResponseError = (getChapterIdResponse400 | getChapterIdResponse404 | getChapterIdResponse500) & {
  headers: Headers;
};

export type getChapterIdResponse = (getChapterIdResponseSuccess | getChapterIdResponseError)

export const getGetChapterIdUrl = (id: string,) => {


  

  return `https://wd.memaydex.online/chapter/${id}`
}

export const getChapterId = async (id: string, options?: RequestInit): Promise<getChapterIdResponse> => {
  
  const res = await fetch(getGetChapterIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getChapterIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getChapterIdResponse
}
  




export const getGetChapterIdQueryKey = (id: string,) => {
    return [
    `https://wd.memaydex.online/chapter/${id}`
    ] as const;
    }

    
export const getGetChapterIdQueryOptions = <TData = Awaited<ReturnType<typeof getChapterId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChapterIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterId>>> = ({ signal }) => getChapterId(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChapterIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChapterId>>>
export type GetChapterIdQueryError = void


export function useGetChapterId<TData = Awaited<ReturnType<typeof getChapterId>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterId>>,
          TError,
          Awaited<ReturnType<typeof getChapterId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterId<TData = Awaited<ReturnType<typeof getChapterId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterId>>,
          TError,
          Awaited<ReturnType<typeof getChapterId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChapterId<TData = Awaited<ReturnType<typeof getChapterId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Chapter
 */

export function useGetChapterId<TData = Awaited<ReturnType<typeof getChapterId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChapterIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Chapter
 */
export type putChapterIdResponse200 = {
  data: Chapter
  status: 200
}

export type putChapterIdResponse400 = {
  data: void
  status: 400
}

export type putChapterIdResponse403 = {
  data: void
  status: 403
}

export type putChapterIdResponse404 = {
  data: void
  status: 404
}

export type putChapterIdResponse409 = {
  data: void
  status: 409
}

export type putChapterIdResponse500 = {
  data: void
  status: 500
}

export type putChapterIdResponseSuccess = (putChapterIdResponse200) & {
  headers: Headers;
};
export type putChapterIdResponseError = (putChapterIdResponse400 | putChapterIdResponse403 | putChapterIdResponse404 | putChapterIdResponse409 | putChapterIdResponse500) & {
  headers: Headers;
};

export type putChapterIdResponse = (putChapterIdResponseSuccess | putChapterIdResponseError)

export const getPutChapterIdUrl = (id: string,) => {


  

  return `https://wd.memaydex.online/chapter/${id}`
}

export const putChapterId = async (id: string,
    controllersUpdateChapterRequest: ControllersUpdateChapterRequest, options?: RequestInit): Promise<putChapterIdResponse> => {
  
  const res = await fetch(getPutChapterIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      controllersUpdateChapterRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putChapterIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putChapterIdResponse
}
  



export const getPutChapterIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChapterId>>, TError,{id: string;data: ControllersUpdateChapterRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putChapterId>>, TError,{id: string;data: ControllersUpdateChapterRequest}, TContext> => {

const mutationKey = ['putChapterId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putChapterId>>, {id: string;data: ControllersUpdateChapterRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putChapterId(id,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutChapterIdMutationResult = NonNullable<Awaited<ReturnType<typeof putChapterId>>>
    export type PutChapterIdMutationBody = ControllersUpdateChapterRequest
    export type PutChapterIdMutationError = void

    /**
 * @summary Update Chapter
 */
export const usePutChapterId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChapterId>>, TError,{id: string;data: ControllersUpdateChapterRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putChapterId>>,
        TError,
        {id: string;data: ControllersUpdateChapterRequest},
        TContext
      > => {
      return useMutation(getPutChapterIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Chapter
 */
export type deleteChapterIdResponse204 = {
  data: void
  status: 204
}

export type deleteChapterIdResponse400 = {
  data: void
  status: 400
}

export type deleteChapterIdResponse403 = {
  data: void
  status: 403
}

export type deleteChapterIdResponse404 = {
  data: void
  status: 404
}

export type deleteChapterIdResponse500 = {
  data: void
  status: 500
}

export type deleteChapterIdResponseSuccess = (deleteChapterIdResponse204) & {
  headers: Headers;
};
export type deleteChapterIdResponseError = (deleteChapterIdResponse400 | deleteChapterIdResponse403 | deleteChapterIdResponse404 | deleteChapterIdResponse500) & {
  headers: Headers;
};

export type deleteChapterIdResponse = (deleteChapterIdResponseSuccess | deleteChapterIdResponseError)

export const getDeleteChapterIdUrl = (id: string,) => {


  

  return `https://wd.memaydex.online/chapter/${id}`
}

export const deleteChapterId = async (id: string, options?: RequestInit): Promise<deleteChapterIdResponse> => {
  
  const res = await fetch(getDeleteChapterIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteChapterIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteChapterIdResponse
}
  



export const getDeleteChapterIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChapterId>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChapterId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteChapterId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChapterId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteChapterId(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChapterIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChapterId>>>
    
    export type DeleteChapterIdMutationError = void

    /**
 * @summary Remove Chapter
 */
export const useDeleteChapterId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChapterId>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteChapterId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteChapterIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Aggregated Chapter List
 */
export type getMangaIdAggregateResponse200 = {
  data: ChapterAggregateResponse
  status: 200
}

export type getMangaIdAggregateResponse400 = {
  data: void
  status: 400
}

export type getMangaIdAggregateResponse404 = {
  data: void
  status: 404
}

export type getMangaIdAggregateResponse500 = {
  data: void
  status: 500
}

export type getMangaIdAggregateResponseSuccess = (getMangaIdAggregateResponse200) & {
  headers: Headers;
};
export type getMangaIdAggregateResponseError = (getMangaIdAggregateResponse400 | getMangaIdAggregateResponse404 | getMangaIdAggregateResponse500) & {
  headers: Headers;
};

export type getMangaIdAggregateResponse = (getMangaIdAggregateResponseSuccess | getMangaIdAggregateResponseError)

export const getGetMangaIdAggregateUrl = (id: string,
    params?: GetMangaIdAggregateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/manga/${id}/aggregate?${stringifiedParams}` : `https://wd.memaydex.online/manga/${id}/aggregate`
}

export const getMangaIdAggregate = async (id: string,
    params?: GetMangaIdAggregateParams, options?: RequestInit): Promise<getMangaIdAggregateResponse> => {
  
  const res = await fetch(getGetMangaIdAggregateUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMangaIdAggregateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMangaIdAggregateResponse
}
  




export const getGetMangaIdAggregateQueryKey = (id: string,
    params?: GetMangaIdAggregateParams,) => {
    return [
    `https://wd.memaydex.online/manga/${id}/aggregate`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMangaIdAggregateQueryOptions = <TData = Awaited<ReturnType<typeof getMangaIdAggregate>>, TError = void>(id: string,
    params?: GetMangaIdAggregateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMangaIdAggregateQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaIdAggregate>>> = ({ signal }) => getMangaIdAggregate(id,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMangaIdAggregateQueryResult = NonNullable<Awaited<ReturnType<typeof getMangaIdAggregate>>>
export type GetMangaIdAggregateQueryError = void


export function useGetMangaIdAggregate<TData = Awaited<ReturnType<typeof getMangaIdAggregate>>, TError = void>(
 id: string,
    params: undefined |  GetMangaIdAggregateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdAggregate>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdAggregate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMangaIdAggregate<TData = Awaited<ReturnType<typeof getMangaIdAggregate>>, TError = void>(
 id: string,
    params?: GetMangaIdAggregateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdAggregate>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdAggregate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMangaIdAggregate<TData = Awaited<ReturnType<typeof getMangaIdAggregate>>, TError = void>(
 id: string,
    params?: GetMangaIdAggregateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Aggregated Chapter List
 */

export function useGetMangaIdAggregate<TData = Awaited<ReturnType<typeof getMangaIdAggregate>>, TError = void>(
 id: string,
    params?: GetMangaIdAggregateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdAggregate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMangaIdAggregateQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Chapter List
 */
export type getMangaIdChaptersResponse200 = {
  data: ChapterFeedResponse
  status: 200
}

export type getMangaIdChaptersResponse400 = {
  data: void
  status: 400
}

export type getMangaIdChaptersResponse404 = {
  data: void
  status: 404
}

export type getMangaIdChaptersResponse500 = {
  data: void
  status: 500
}

export type getMangaIdChaptersResponseSuccess = (getMangaIdChaptersResponse200) & {
  headers: Headers;
};
export type getMangaIdChaptersResponseError = (getMangaIdChaptersResponse400 | getMangaIdChaptersResponse404 | getMangaIdChaptersResponse500) & {
  headers: Headers;
};

export type getMangaIdChaptersResponse = (getMangaIdChaptersResponseSuccess | getMangaIdChaptersResponseError)

export const getGetMangaIdChaptersUrl = (id: string,
    params?: GetMangaIdChaptersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://wd.memaydex.online/manga/${id}/chapters?${stringifiedParams}` : `https://wd.memaydex.online/manga/${id}/chapters`
}

export const getMangaIdChapters = async (id: string,
    params?: GetMangaIdChaptersParams, options?: RequestInit): Promise<getMangaIdChaptersResponse> => {
  
  const res = await fetch(getGetMangaIdChaptersUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMangaIdChaptersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMangaIdChaptersResponse
}
  




export const getGetMangaIdChaptersQueryKey = (id: string,
    params?: GetMangaIdChaptersParams,) => {
    return [
    `https://wd.memaydex.online/manga/${id}/chapters`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMangaIdChaptersQueryOptions = <TData = Awaited<ReturnType<typeof getMangaIdChapters>>, TError = void>(id: string,
    params?: GetMangaIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMangaIdChaptersQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaIdChapters>>> = ({ signal }) => getMangaIdChapters(id,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMangaIdChaptersQueryResult = NonNullable<Awaited<ReturnType<typeof getMangaIdChapters>>>
export type GetMangaIdChaptersQueryError = void


export function useGetMangaIdChapters<TData = Awaited<ReturnType<typeof getMangaIdChapters>>, TError = void>(
 id: string,
    params: undefined |  GetMangaIdChaptersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdChapters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMangaIdChapters<TData = Awaited<ReturnType<typeof getMangaIdChapters>>, TError = void>(
 id: string,
    params?: GetMangaIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdChapters>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMangaIdChapters<TData = Awaited<ReturnType<typeof getMangaIdChapters>>, TError = void>(
 id: string,
    params?: GetMangaIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Chapter List
 */

export function useGetMangaIdChapters<TData = Awaited<ReturnType<typeof getMangaIdChapters>>, TError = void>(
 id: string,
    params?: GetMangaIdChaptersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMangaIdChapters>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMangaIdChaptersQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




