/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetMangaTagParams,
  InternalErrorResponse,
  TagFeedResponse,
  ValidationErrorResponse,
} from "../../model";

/**
 * Fetch the normalized tag list from the archived dataset.
 * @summary Get Tag List
 */
export type getMangaTagResponse200 = {
  data: TagFeedResponse;
  status: 200;
};

export type getMangaTagResponse400 = {
  data: ValidationErrorResponse;
  status: 400;
};

export type getMangaTagResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getMangaTagResponseSuccess = getMangaTagResponse200 & {
  headers: Headers;
};
export type getMangaTagResponseError = (
  | getMangaTagResponse400
  | getMangaTagResponse500
) & {
  headers: Headers;
};

export type getMangaTagResponse =
  | getMangaTagResponseSuccess
  | getMangaTagResponseError;

export const getGetMangaTagUrl = (params?: GetMangaTagParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://wd.suicaodex.com/manga/tag?${stringifiedParams}`
    : `http://wd.suicaodex.com/manga/tag`;
};

export const getMangaTag = async (
  params?: GetMangaTagParams,
  options?: RequestInit,
): Promise<getMangaTagResponse> => {
  const res = await fetch(getGetMangaTagUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaTagResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaTagResponse;
};

export const getGetMangaTagQueryKey = (params?: GetMangaTagParams) => {
  return [
    `http://wd.suicaodex.com/manga/tag`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMangaTagQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaTag>>,
  TError = ValidationErrorResponse | InternalErrorResponse,
>(
  params?: GetMangaTagParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTag>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMangaTagQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMangaTag>>> = ({
    signal,
  }) => getMangaTag(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaTag>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaTagQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaTag>>
>;
export type GetMangaTagQueryError =
  | ValidationErrorResponse
  | InternalErrorResponse;

export function useGetMangaTag<
  TData = Awaited<ReturnType<typeof getMangaTag>>,
  TError = ValidationErrorResponse | InternalErrorResponse,
>(
  params: undefined | GetMangaTagParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTag>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaTag>>,
          TError,
          Awaited<ReturnType<typeof getMangaTag>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaTag<
  TData = Awaited<ReturnType<typeof getMangaTag>>,
  TError = ValidationErrorResponse | InternalErrorResponse,
>(
  params?: GetMangaTagParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTag>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaTag>>,
          TError,
          Awaited<ReturnType<typeof getMangaTag>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaTag<
  TData = Awaited<ReturnType<typeof getMangaTag>>,
  TError = ValidationErrorResponse | InternalErrorResponse,
>(
  params?: GetMangaTagParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTag>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Tag List
 */

export function useGetMangaTag<
  TData = Awaited<ReturnType<typeof getMangaTag>>,
  TError = ValidationErrorResponse | InternalErrorResponse,
>(
  params?: GetMangaTagParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMangaTag>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaTagQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
