/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetGroupParams,
  GroupInternalErrorResponse,
  GroupNotFoundErrorResponse,
  GroupValidationErrorResponse,
  ScanlationGroup,
  ScanlationGroupFeedResponse,
} from "../../model";

/**
 * @summary Get Scanlation Group List
 */
export type getGroupResponse200 = {
  data: ScanlationGroupFeedResponse;
  status: 200;
};

export type getGroupResponse400 = {
  data: GroupValidationErrorResponse;
  status: 400;
};

export type getGroupResponse500 = {
  data: GroupInternalErrorResponse;
  status: 500;
};

export type getGroupResponseSuccess = getGroupResponse200 & {
  headers: Headers;
};
export type getGroupResponseError = (
  | getGroupResponse400
  | getGroupResponse500
) & {
  headers: Headers;
};

export type getGroupResponse = getGroupResponseSuccess | getGroupResponseError;

export const getGetGroupUrl = (params?: GetGroupParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://wd.suicaodex.com/group?${stringifiedParams}`
    : `https://wd.suicaodex.com/group`;
};

export const getGroup = async (
  params?: GetGroupParams,
  options?: RequestInit,
): Promise<getGroupResponse> => {
  const res = await fetch(getGetGroupUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGroupResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getGroupResponse;
};

export const getGetGroupQueryKey = (params?: GetGroupParams) => {
  return [
    `https://wd.suicaodex.com/group`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGroupQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroup>>,
  TError = GroupValidationErrorResponse | GroupInternalErrorResponse,
>(
  params?: GetGroupParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroup>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGroupQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroup>>> = ({
    signal,
  }) => getGroup(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroup>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGroupQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGroup>>
>;
export type GetGroupQueryError =
  | GroupValidationErrorResponse
  | GroupInternalErrorResponse;

export function useGetGroup<
  TData = Awaited<ReturnType<typeof getGroup>>,
  TError = GroupValidationErrorResponse | GroupInternalErrorResponse,
>(
  params: undefined | GetGroupParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroup>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroup>>,
          TError,
          Awaited<ReturnType<typeof getGroup>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroup<
  TData = Awaited<ReturnType<typeof getGroup>>,
  TError = GroupValidationErrorResponse | GroupInternalErrorResponse,
>(
  params?: GetGroupParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroup>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroup>>,
          TError,
          Awaited<ReturnType<typeof getGroup>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroup<
  TData = Awaited<ReturnType<typeof getGroup>>,
  TError = GroupValidationErrorResponse | GroupInternalErrorResponse,
>(
  params?: GetGroupParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroup>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Scanlation Group List
 */

export function useGetGroup<
  TData = Awaited<ReturnType<typeof getGroup>>,
  TError = GroupValidationErrorResponse | GroupInternalErrorResponse,
>(
  params?: GetGroupParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroup>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGroupQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Scanlation Group
 */
export type getGroupIdResponse200 = {
  data: ScanlationGroup;
  status: 200;
};

export type getGroupIdResponse404 = {
  data: GroupNotFoundErrorResponse;
  status: 404;
};

export type getGroupIdResponse500 = {
  data: GroupInternalErrorResponse;
  status: 500;
};

export type getGroupIdResponseSuccess = getGroupIdResponse200 & {
  headers: Headers;
};
export type getGroupIdResponseError = (
  | getGroupIdResponse404
  | getGroupIdResponse500
) & {
  headers: Headers;
};

export type getGroupIdResponse =
  | getGroupIdResponseSuccess
  | getGroupIdResponseError;

export const getGetGroupIdUrl = (id: string) => {
  return `https://wd.suicaodex.com/group/${id}`;
};

export const getGroupId = async (
  id: string,
  options?: RequestInit,
): Promise<getGroupIdResponse> => {
  const res = await fetch(getGetGroupIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGroupIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getGroupIdResponse;
};

export const getGetGroupIdQueryKey = (id: string) => {
  return [`https://wd.suicaodex.com/group/${id}`] as const;
};

export const getGetGroupIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroupId>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroupId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGroupIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupId>>> = ({
    signal,
  }) => getGroupId(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroupId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGroupIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGroupId>>
>;
export type GetGroupIdQueryError =
  | GroupNotFoundErrorResponse
  | GroupInternalErrorResponse;

export function useGetGroupId<
  TData = Awaited<ReturnType<typeof getGroupId>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroupId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupId>>,
          TError,
          Awaited<ReturnType<typeof getGroupId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroupId<
  TData = Awaited<ReturnType<typeof getGroupId>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroupId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupId>>,
          TError,
          Awaited<ReturnType<typeof getGroupId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroupId<
  TData = Awaited<ReturnType<typeof getGroupId>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroupId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Scanlation Group
 */

export function useGetGroupId<
  TData = Awaited<ReturnType<typeof getGroupId>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGroupId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGroupIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
