/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moetruyen Public API
 * Unofficial read-only REST API for [MoeTruyen](https://moetruyen.net/).

Full features will be added in the future (chắc thế)

Github: [TNTKien/moetruyen-public-api](https://github.com/TNTKien/moetruyen-public-api), [dex593/web1 (MoeTruyen)](https://github.com/dex593/web1)

NOTE:
- All API endpoints have a global rate limit of 7 requests per second per IP.
- To avoid future issues, include the Origin: https://suicaodex.com or https://moetruyen.net headers when making API requests.
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetV1Manga200,
  GetV1Manga400,
  GetV1MangaById200,
  GetV1MangaById404,
  GetV1MangaByIdChapters200,
  GetV1MangaByIdChapters404,
  GetV1MangaParams,
  GetV1MangaRandom200,
  GetV1MangaRandom400,
  GetV1MangaRandomParams,
  GetV1MangaTop200,
  GetV1MangaTop400,
  GetV1MangaTopParams,
} from "../../model";

/**
 * Returns paginated public manga rankings.
 * @summary List top public manga
 */
export type getV1MangaTopResponse200 = {
  data: GetV1MangaTop200;
  status: 200;
};

export type getV1MangaTopResponse400 = {
  data: GetV1MangaTop400;
  status: 400;
};

export type getV1MangaTopResponseSuccess = getV1MangaTopResponse200 & {
  headers: Headers;
};
export type getV1MangaTopResponseError = getV1MangaTopResponse400 & {
  headers: Headers;
};

export type getV1MangaTopResponse =
  | getV1MangaTopResponseSuccess
  | getV1MangaTopResponseError;

export const getGetV1MangaTopUrl = (params?: GetV1MangaTopParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://moe.suicaodex.com/v1/manga/top?${stringifiedParams}`
    : `https://moe.suicaodex.com/v1/manga/top`;
};

export const getV1MangaTop = async (
  params?: GetV1MangaTopParams,
  options?: RequestInit,
): Promise<getV1MangaTopResponse> => {
  const res = await fetch(getGetV1MangaTopUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MangaTopResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1MangaTopResponse;
};

export const getGetV1MangaTopQueryKey = (params?: GetV1MangaTopParams) => {
  return [
    `https://moe.suicaodex.com/v1/manga/top`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetV1MangaTopQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1MangaTop>>,
  TError = GetV1MangaTop400,
>(
  params?: GetV1MangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1MangaTopQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1MangaTop>>> = ({
    signal,
  }) => getV1MangaTop(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1MangaTop>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1MangaTopQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1MangaTop>>
>;
export type GetV1MangaTopQueryError = GetV1MangaTop400;

export function useGetV1MangaTop<
  TData = Awaited<ReturnType<typeof getV1MangaTop>>,
  TError = GetV1MangaTop400,
>(
  params: undefined | GetV1MangaTopParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaTop>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaTop>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaTop<
  TData = Awaited<ReturnType<typeof getV1MangaTop>>,
  TError = GetV1MangaTop400,
>(
  params?: GetV1MangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaTop>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaTop>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaTop>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaTop<
  TData = Awaited<ReturnType<typeof getV1MangaTop>>,
  TError = GetV1MangaTop400,
>(
  params?: GetV1MangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List top public manga
 */

export function useGetV1MangaTop<
  TData = Awaited<ReturnType<typeof getV1MangaTop>>,
  TError = GetV1MangaTop400,
>(
  params?: GetV1MangaTopParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaTop>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV1MangaTopQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns 1 to 10 random public manga items using the standard manga list item shape.
 * @summary List random public manga
 */
export type getV1MangaRandomResponse200 = {
  data: GetV1MangaRandom200;
  status: 200;
};

export type getV1MangaRandomResponse400 = {
  data: GetV1MangaRandom400;
  status: 400;
};

export type getV1MangaRandomResponseSuccess = getV1MangaRandomResponse200 & {
  headers: Headers;
};
export type getV1MangaRandomResponseError = getV1MangaRandomResponse400 & {
  headers: Headers;
};

export type getV1MangaRandomResponse =
  | getV1MangaRandomResponseSuccess
  | getV1MangaRandomResponseError;

export const getGetV1MangaRandomUrl = (params?: GetV1MangaRandomParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://moe.suicaodex.com/v1/manga/random?${stringifiedParams}`
    : `https://moe.suicaodex.com/v1/manga/random`;
};

export const getV1MangaRandom = async (
  params?: GetV1MangaRandomParams,
  options?: RequestInit,
): Promise<getV1MangaRandomResponse> => {
  const res = await fetch(getGetV1MangaRandomUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MangaRandomResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1MangaRandomResponse;
};

export const getGetV1MangaRandomQueryKey = (
  params?: GetV1MangaRandomParams,
) => {
  return [
    `https://moe.suicaodex.com/v1/manga/random`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetV1MangaRandomQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1MangaRandom>>,
  TError = GetV1MangaRandom400,
>(
  params?: GetV1MangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaRandom>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetV1MangaRandomQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getV1MangaRandom>>
  > = ({ signal }) => getV1MangaRandom(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1MangaRandom>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1MangaRandomQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1MangaRandom>>
>;
export type GetV1MangaRandomQueryError = GetV1MangaRandom400;

export function useGetV1MangaRandom<
  TData = Awaited<ReturnType<typeof getV1MangaRandom>>,
  TError = GetV1MangaRandom400,
>(
  params: undefined | GetV1MangaRandomParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaRandom>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaRandom>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaRandom>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaRandom<
  TData = Awaited<ReturnType<typeof getV1MangaRandom>>,
  TError = GetV1MangaRandom400,
>(
  params?: GetV1MangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaRandom>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaRandom>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaRandom>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaRandom<
  TData = Awaited<ReturnType<typeof getV1MangaRandom>>,
  TError = GetV1MangaRandom400,
>(
  params?: GetV1MangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaRandom>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List random public manga
 */

export function useGetV1MangaRandom<
  TData = Awaited<ReturnType<typeof getV1MangaRandom>>,
  TError = GetV1MangaRandom400,
>(
  params?: GetV1MangaRandomParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaRandom>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV1MangaRandomQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns paginated public manga results with optional search, genre, status, sort, and hasChapters filters.
 * @summary List public manga
 */
export type getV1MangaResponse200 = {
  data: GetV1Manga200;
  status: 200;
};

export type getV1MangaResponse400 = {
  data: GetV1Manga400;
  status: 400;
};

export type getV1MangaResponseSuccess = getV1MangaResponse200 & {
  headers: Headers;
};
export type getV1MangaResponseError = getV1MangaResponse400 & {
  headers: Headers;
};

export type getV1MangaResponse =
  | getV1MangaResponseSuccess
  | getV1MangaResponseError;

export const getGetV1MangaUrl = (params?: GetV1MangaParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://moe.suicaodex.com/v1/manga?${stringifiedParams}`
    : `https://moe.suicaodex.com/v1/manga`;
};

export const getV1Manga = async (
  params?: GetV1MangaParams,
  options?: RequestInit,
): Promise<getV1MangaResponse> => {
  const res = await fetch(getGetV1MangaUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MangaResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1MangaResponse;
};

export const getGetV1MangaQueryKey = (params?: GetV1MangaParams) => {
  return [
    `https://moe.suicaodex.com/v1/manga`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetV1MangaQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1Manga>>,
  TError = GetV1Manga400,
>(
  params?: GetV1MangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1Manga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1MangaQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Manga>>> = ({
    signal,
  }) => getV1Manga(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1Manga>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1MangaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1Manga>>
>;
export type GetV1MangaQueryError = GetV1Manga400;

export function useGetV1Manga<
  TData = Awaited<ReturnType<typeof getV1Manga>>,
  TError = GetV1Manga400,
>(
  params: undefined | GetV1MangaParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1Manga>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Manga>>,
          TError,
          Awaited<ReturnType<typeof getV1Manga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1Manga<
  TData = Awaited<ReturnType<typeof getV1Manga>>,
  TError = GetV1Manga400,
>(
  params?: GetV1MangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1Manga>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Manga>>,
          TError,
          Awaited<ReturnType<typeof getV1Manga>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1Manga<
  TData = Awaited<ReturnType<typeof getV1Manga>>,
  TError = GetV1Manga400,
>(
  params?: GetV1MangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1Manga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List public manga
 */

export function useGetV1Manga<
  TData = Awaited<ReturnType<typeof getV1Manga>>,
  TError = GetV1Manga400,
>(
  params?: GetV1MangaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1Manga>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV1MangaQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the public manga detail payload for a manga id.
 * @summary Get manga detail
 */
export type getV1MangaByIdResponse200 = {
  data: GetV1MangaById200;
  status: 200;
};

export type getV1MangaByIdResponse404 = {
  data: GetV1MangaById404;
  status: 404;
};

export type getV1MangaByIdResponseSuccess = getV1MangaByIdResponse200 & {
  headers: Headers;
};
export type getV1MangaByIdResponseError = getV1MangaByIdResponse404 & {
  headers: Headers;
};

export type getV1MangaByIdResponse =
  | getV1MangaByIdResponseSuccess
  | getV1MangaByIdResponseError;

export const getGetV1MangaByIdUrl = (id: number) => {
  return `https://moe.suicaodex.com/v1/manga/${id}`;
};

export const getV1MangaById = async (
  id: number,
  options?: RequestInit,
): Promise<getV1MangaByIdResponse> => {
  const res = await fetch(getGetV1MangaByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MangaByIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1MangaByIdResponse;
};

export const getGetV1MangaByIdQueryKey = (id: number) => {
  return [`https://moe.suicaodex.com/v1/manga/${id}`] as const;
};

export const getGetV1MangaByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1MangaById>>,
  TError = GetV1MangaById404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1MangaByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1MangaById>>> = ({
    signal,
  }) => getV1MangaById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1MangaById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1MangaByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1MangaById>>
>;
export type GetV1MangaByIdQueryError = GetV1MangaById404;

export function useGetV1MangaById<
  TData = Awaited<ReturnType<typeof getV1MangaById>>,
  TError = GetV1MangaById404,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaById>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaById>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaById<
  TData = Awaited<ReturnType<typeof getV1MangaById>>,
  TError = GetV1MangaById404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaById>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaById>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaById<
  TData = Awaited<ReturnType<typeof getV1MangaById>>,
  TError = GetV1MangaById404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get manga detail
 */

export function useGetV1MangaById<
  TData = Awaited<ReturnType<typeof getV1MangaById>>,
  TError = GetV1MangaById404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getV1MangaById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV1MangaByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns public chapter metadata for a manga id ordered by latest chapter first.
 * @summary List public manga chapters
 */
export type getV1MangaByIdChaptersResponse200 = {
  data: GetV1MangaByIdChapters200;
  status: 200;
};

export type getV1MangaByIdChaptersResponse404 = {
  data: GetV1MangaByIdChapters404;
  status: 404;
};

export type getV1MangaByIdChaptersResponseSuccess =
  getV1MangaByIdChaptersResponse200 & {
    headers: Headers;
  };
export type getV1MangaByIdChaptersResponseError =
  getV1MangaByIdChaptersResponse404 & {
    headers: Headers;
  };

export type getV1MangaByIdChaptersResponse =
  | getV1MangaByIdChaptersResponseSuccess
  | getV1MangaByIdChaptersResponseError;

export const getGetV1MangaByIdChaptersUrl = (id: number) => {
  return `https://moe.suicaodex.com/v1/manga/${id}/chapters`;
};

export const getV1MangaByIdChapters = async (
  id: number,
  options?: RequestInit,
): Promise<getV1MangaByIdChaptersResponse> => {
  const res = await fetch(getGetV1MangaByIdChaptersUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MangaByIdChaptersResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getV1MangaByIdChaptersResponse;
};

export const getGetV1MangaByIdChaptersQueryKey = (id: number) => {
  return [`https://moe.suicaodex.com/v1/manga/${id}/chapters`] as const;
};

export const getGetV1MangaByIdChaptersQueryOptions = <
  TData = Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
  TError = GetV1MangaByIdChapters404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetV1MangaByIdChaptersQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getV1MangaByIdChapters>>
  > = ({ signal }) => getV1MangaByIdChapters(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetV1MangaByIdChaptersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getV1MangaByIdChapters>>
>;
export type GetV1MangaByIdChaptersQueryError = GetV1MangaByIdChapters404;

export function useGetV1MangaByIdChapters<
  TData = Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
  TError = GetV1MangaByIdChapters404,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaByIdChapters>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaByIdChapters<
  TData = Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
  TError = GetV1MangaByIdChapters404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
          TError,
          Awaited<ReturnType<typeof getV1MangaByIdChapters>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetV1MangaByIdChapters<
  TData = Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
  TError = GetV1MangaByIdChapters404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List public manga chapters
 */

export function useGetV1MangaByIdChapters<
  TData = Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
  TError = GetV1MangaByIdChapters404,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getV1MangaByIdChapters>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetV1MangaByIdChaptersQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
