/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChapterInternalErrorResponse,
  ChapterNotFoundErrorResponse,
  ChapterStats,
  GroupInternalErrorResponse,
  GroupNotFoundErrorResponse,
  InternalErrorResponse,
  MangaNotFoundErrorResponse,
  MangaStats,
  ScanlationGroupStats,
} from "../../model";

/**
 * @summary Get Chapter Statistics
 */
export type getChapterIdStatisticsResponse200 = {
  data: ChapterStats;
  status: 200;
};

export type getChapterIdStatisticsResponse404 = {
  data: ChapterNotFoundErrorResponse;
  status: 404;
};

export type getChapterIdStatisticsResponse500 = {
  data: ChapterInternalErrorResponse;
  status: 500;
};

export type getChapterIdStatisticsResponseSuccess =
  getChapterIdStatisticsResponse200 & {
    headers: Headers;
  };
export type getChapterIdStatisticsResponseError = (
  | getChapterIdStatisticsResponse404
  | getChapterIdStatisticsResponse500
) & {
  headers: Headers;
};

export type getChapterIdStatisticsResponse =
  | getChapterIdStatisticsResponseSuccess
  | getChapterIdStatisticsResponseError;

export const getGetChapterIdStatisticsUrl = (id: string) => {
  return `http://wd.suicaodex.com/chapter/${id}/statistics`;
};

export const getChapterIdStatistics = async (
  id: string,
  options?: RequestInit,
): Promise<getChapterIdStatisticsResponse> => {
  const res = await fetch(getGetChapterIdStatisticsUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getChapterIdStatisticsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChapterIdStatisticsResponse;
};

export const getGetChapterIdStatisticsQueryKey = (id: string) => {
  return [`http://wd.suicaodex.com/chapter/${id}/statistics`] as const;
};

export const getGetChapterIdStatisticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterIdStatistics>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChapterIdStatisticsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChapterIdStatistics>>
  > = ({ signal }) => getChapterIdStatistics(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChapterIdStatistics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChapterIdStatisticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChapterIdStatistics>>
>;
export type GetChapterIdStatisticsQueryError =
  | ChapterNotFoundErrorResponse
  | ChapterInternalErrorResponse;

export function useGetChapterIdStatistics<
  TData = Awaited<ReturnType<typeof getChapterIdStatistics>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getChapterIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterIdStatistics<
  TData = Awaited<ReturnType<typeof getChapterIdStatistics>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChapterIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getChapterIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChapterIdStatistics<
  TData = Awaited<ReturnType<typeof getChapterIdStatistics>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chapter Statistics
 */

export function useGetChapterIdStatistics<
  TData = Awaited<ReturnType<typeof getChapterIdStatistics>>,
  TError = ChapterNotFoundErrorResponse | ChapterInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChapterIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChapterIdStatisticsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Group Statistics
 */
export type getGroupIdStatisticsResponse200 = {
  data: ScanlationGroupStats;
  status: 200;
};

export type getGroupIdStatisticsResponse404 = {
  data: GroupNotFoundErrorResponse;
  status: 404;
};

export type getGroupIdStatisticsResponse500 = {
  data: GroupInternalErrorResponse;
  status: 500;
};

export type getGroupIdStatisticsResponseSuccess =
  getGroupIdStatisticsResponse200 & {
    headers: Headers;
  };
export type getGroupIdStatisticsResponseError = (
  | getGroupIdStatisticsResponse404
  | getGroupIdStatisticsResponse500
) & {
  headers: Headers;
};

export type getGroupIdStatisticsResponse =
  | getGroupIdStatisticsResponseSuccess
  | getGroupIdStatisticsResponseError;

export const getGetGroupIdStatisticsUrl = (id: string) => {
  return `http://wd.suicaodex.com/group/${id}/statistics`;
};

export const getGroupIdStatistics = async (
  id: string,
  options?: RequestInit,
): Promise<getGroupIdStatisticsResponse> => {
  const res = await fetch(getGetGroupIdStatisticsUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGroupIdStatisticsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getGroupIdStatisticsResponse;
};

export const getGetGroupIdStatisticsQueryKey = (id: string) => {
  return [`http://wd.suicaodex.com/group/${id}/statistics`] as const;
};

export const getGetGroupIdStatisticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroupIdStatistics>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGroupIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGroupIdStatisticsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGroupIdStatistics>>
  > = ({ signal }) => getGroupIdStatistics(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroupIdStatistics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGroupIdStatisticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGroupIdStatistics>>
>;
export type GetGroupIdStatisticsQueryError =
  | GroupNotFoundErrorResponse
  | GroupInternalErrorResponse;

export function useGetGroupIdStatistics<
  TData = Awaited<ReturnType<typeof getGroupIdStatistics>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGroupIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getGroupIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroupIdStatistics<
  TData = Awaited<ReturnType<typeof getGroupIdStatistics>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGroupIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getGroupIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGroupIdStatistics<
  TData = Awaited<ReturnType<typeof getGroupIdStatistics>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGroupIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Group Statistics
 */

export function useGetGroupIdStatistics<
  TData = Awaited<ReturnType<typeof getGroupIdStatistics>>,
  TError = GroupNotFoundErrorResponse | GroupInternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGroupIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGroupIdStatisticsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Fetch normalized manga statistics from the archived dataset.
 * @summary Get Manga Statistics
 */
export type getMangaIdStatisticsResponse200 = {
  data: MangaStats;
  status: 200;
};

export type getMangaIdStatisticsResponse404 = {
  data: MangaNotFoundErrorResponse;
  status: 404;
};

export type getMangaIdStatisticsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getMangaIdStatisticsResponseSuccess =
  getMangaIdStatisticsResponse200 & {
    headers: Headers;
  };
export type getMangaIdStatisticsResponseError = (
  | getMangaIdStatisticsResponse404
  | getMangaIdStatisticsResponse500
) & {
  headers: Headers;
};

export type getMangaIdStatisticsResponse =
  | getMangaIdStatisticsResponseSuccess
  | getMangaIdStatisticsResponseError;

export const getGetMangaIdStatisticsUrl = (id: string) => {
  return `http://wd.suicaodex.com/manga/${id}/statistics`;
};

export const getMangaIdStatistics = async (
  id: string,
  options?: RequestInit,
): Promise<getMangaIdStatisticsResponse> => {
  const res = await fetch(getGetMangaIdStatisticsUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMangaIdStatisticsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMangaIdStatisticsResponse;
};

export const getGetMangaIdStatisticsQueryKey = (id: string) => {
  return [`http://wd.suicaodex.com/manga/${id}/statistics`] as const;
};

export const getGetMangaIdStatisticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMangaIdStatistics>>,
  TError = MangaNotFoundErrorResponse | InternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMangaIdStatisticsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMangaIdStatistics>>
  > = ({ signal }) => getMangaIdStatistics(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMangaIdStatistics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMangaIdStatisticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMangaIdStatistics>>
>;
export type GetMangaIdStatisticsQueryError =
  | MangaNotFoundErrorResponse
  | InternalErrorResponse;

export function useGetMangaIdStatistics<
  TData = Awaited<ReturnType<typeof getMangaIdStatistics>>,
  TError = MangaNotFoundErrorResponse | InternalErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdStatistics<
  TData = Awaited<ReturnType<typeof getMangaIdStatistics>>,
  TError = MangaNotFoundErrorResponse | InternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdStatistics>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMangaIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getMangaIdStatistics>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMangaIdStatistics<
  TData = Awaited<ReturnType<typeof getMangaIdStatistics>>,
  TError = MangaNotFoundErrorResponse | InternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Manga Statistics
 */

export function useGetMangaIdStatistics<
  TData = Awaited<ReturnType<typeof getMangaIdStatistics>>,
  TError = MangaNotFoundErrorResponse | InternalErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMangaIdStatistics>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMangaIdStatisticsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
