/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { ChapterGroupSummary } from "./chapterGroupSummary";
import type { ChapterMangaSummary } from "./chapterMangaSummary";
import type { ChapterStats } from "./chapterStats";
import type { ChapterThreadSummary } from "./chapterThreadSummary";
import type { ChapterUserSummary } from "./chapterUserSummary";

export interface ChapterDetailRelationships {
  groups?: ChapterGroupSummary[];
  manga?: ChapterMangaSummary;
  stats?: ChapterStats;
  thread?: ChapterThreadSummary;
  uploader?: ChapterUserSummary;
  [key: string]: unknown | null;
}
