/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */

export type ControllersCreateMangaRelationRequestType = typeof ControllersCreateMangaRelationRequestType[keyof typeof ControllersCreateMangaRelationRequestType];


export const ControllersCreateMangaRelationRequestType = {
  main_story: 'main_story',
  side_story: 'side_story',
  prequel: 'prequel',
  sequel: 'sequel',
  adapted_from: 'adapted_from',
  spin_off: 'spin_off',
  based_on: 'based_on',
  doujinshi: 'doujinshi',
  monochrome: 'monochrome',
  colored: 'colored',
  preserialization: 'preserialization',
  serialization: 'serialization',
  alternate_story: 'alternate_story',
  alternate_version: 'alternate_version',
  same_franchise: 'same_franchise',
  shared_universe: 'shared_universe',
} as const;
