/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetChapterUpdatesContentRatingItem =
  (typeof GetChapterUpdatesContentRatingItem)[keyof typeof GetChapterUpdatesContentRatingItem];

export const GetChapterUpdatesContentRatingItem = {
  safe: "safe",
  suggestive: "suggestive",
  erotica: "erotica",
  pornographic: "pornographic",
} as const;
