/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { GetChapterTopContentRatingItem } from "./getChapterTopContentRatingItem";
import type { GetChapterTopTime } from "./getChapterTopTime";

export type GetChapterTopParams = {
  /**
   * Default: safe, suggestive, erotica
   * @nullable
   */
  contentRating?: GetChapterTopContentRatingItem[] | null;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  page?: number | null;
  /**
   * @nullable
   */
  time?: GetChapterTopTime;
};
