/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetChapterOrder =
  | (typeof GetChapterOrder)[keyof typeof GetChapterOrder]
  | null;

export const GetChapterOrder = {
  asc: "asc",
  desc: "desc",
} as const;
