/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetChapterTmod =
  | (typeof GetChapterTmod)[keyof typeof GetChapterTmod]
  | null;

export const GetChapterTmod = {
  NUMBER_0: "0",
  NUMBER_1: "1",
  AND: "AND",
  OR: "OR",
} as const;
