/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { GetChapterFeedContentRatingItem } from "./getChapterFeedContentRatingItem";
import type { GetChapterFeedDemographicItem } from "./getChapterFeedDemographicItem";
import type { GetChapterFeedOrder } from "./getChapterFeedOrder";
import type { GetChapterFeedStatusItem } from "./getChapterFeedStatusItem";
import type { GetChapterFeedTmod } from "./getChapterFeedTmod";
import type { GetChapterFeedTxmod } from "./getChapterFeedTxmod";

export type GetChapterFeedParams = {
  /**
   * Artists to filter by (array of IDs)
   * @nullable
   */
  artist?: string[] | null;
  /**
   * Authors to filter by (array of IDs)
   * @nullable
   */
  author?: string[] | null;
  /**
   * @nullable
   */
  authorOrArtist?: string | null;
  /**
   * Default: safe, suggestive, erotica
   * @nullable
   */
  contentRating?: GetChapterFeedContentRatingItem[] | null;
  /**
   * @nullable
   */
  demographic?: GetChapterFeedDemographicItem[] | null;
  /**
   * Groups to include (array of IDs)
   * @nullable
   */
  group?: string[] | null;
  /**
   * Groups to exclude (array of IDs)
   * @nullable
   */
  groupx?: string[] | null;
  /**
   * Original language(s) to include
   * @nullable
   */
  lang?: string[] | null;
  /**
   * Original language(s) to exclude
   * @nullable
   */
  langx?: string[] | null;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  limit?: number | null;
  /**
   * @nullable
   */
  order?: GetChapterFeedOrder;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  page?: number | null;
  /**
   * @nullable
   */
  status?: GetChapterFeedStatusItem[] | null;
  /**
   * Tags to include
   * @nullable
   */
  tag?: string[] | null;
  /**
   * Tags to exclude
   * @nullable
   */
  tagx?: string[] | null;
  /**
   * Translated language(s) to include
   * @nullable
   */
  tlang?: string[] | null;
  /**
   * Translated language(s) to exclude
   * @nullable
   */
  tlangx?: string[] | null;
  /**
   * Mode for tag inclusion
   * @nullable
   */
  tmod?: GetChapterFeedTmod;
  /**
   * Mode for tag exclusion
   * @nullable
   */
  txmod?: GetChapterFeedTxmod;
  /**
   * Uploaders to include
   * @nullable
   */
  uploader?: string[] | null;
  /**
   * Uploaders to exclude
   * @nullable
   */
  uploaderx?: string[] | null;
};
