/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetChapterTopTime =
  | (typeof GetChapterTopTime)[keyof typeof GetChapterTopTime]
  | null;

export const GetChapterTopTime = {
  "24h": "24h",
  "7d": "7d",
  "30d": "30d",
} as const;
