/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetGroupParams = {
  /**
   * @maxItems 100
   * @nullable
   */
  id?: string[] | null;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  limit?: number | null;
  /**
   * @nullable
   */
  name?: string | null;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  page?: number | null;
};
