/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetMangaIdChaptersSort =
  | (typeof GetMangaIdChaptersSort)[keyof typeof GetMangaIdChaptersSort]
  | null;

export const GetMangaIdChaptersSort = {
  publishedAt: "publishedAt",
  name: "name",
} as const;
