/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetMangaRandomDemographicItem =
  (typeof GetMangaRandomDemographicItem)[keyof typeof GetMangaRandomDemographicItem];

export const GetMangaRandomDemographicItem = {
  shounen: "shounen",
  shoujo: "shoujo",
  josei: "josei",
  seinen: "seinen",
  none: "none",
} as const;
