/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { GetMangaRandomContentRatingItem } from "./getMangaRandomContentRatingItem";
import type { GetMangaRandomDemographicItem } from "./getMangaRandomDemographicItem";
import type { GetMangaRandomStatusItem } from "./getMangaRandomStatusItem";
import type { GetMangaRandomTmod } from "./getMangaRandomTmod";
import type { GetMangaRandomTxmod } from "./getMangaRandomTxmod";

export type GetMangaRandomParams = {
  /**
   * Artists to filter by (array of IDs)
   * @nullable
   */
  artist?: string[] | null;
  /**
   * Authors to filter by (array of IDs)
   * @nullable
   */
  author?: string[] | null;
  /**
   * @nullable
   */
  authorOrArtist?: string | null;
  /**
   * Default: safe, suggestive, erotica
   * @nullable
   */
  contentRating?: GetMangaRandomContentRatingItem[] | null;
  /**
   * @nullable
   */
  demographic?: GetMangaRandomDemographicItem[] | null;
  /**
   * @nullable
   */
  group?: string | null;
  /**
   * @nullable
   */
  hasChapters?: boolean | null;
  /**
   * Original language(s) to include
   * @nullable
   */
  lang?: string[] | null;
  /**
   * Original language(s) to exclude
   * @nullable
   */
  langx?: string[] | null;
  /**
   * @nullable
   */
  status?: GetMangaRandomStatusItem[] | null;
  /**
   * Tags to include (array of IDs)
   * @nullable
   */
  tag?: string[] | null;
  /**
   * Tags to exclude (array of IDs)
   * @nullable
   */
  tagx?: string[] | null;
  /**
   * Mode for tag inclusion
   * @nullable
   */
  tmod?: GetMangaRandomTmod;
  /**
   * Mode for tag exclusion
   * @nullable
   */
  txmod?: GetMangaRandomTxmod;
  /**
   * Start of the release year range
   * @minimum 1900
   * @maximum 2100
   * @nullable
   */
  yearFrom?: number | null;
  /**
   * End of the release year range
   * @minimum 1900
   * @maximum 2100
   * @nullable
   */
  yearTo?: number | null;
};
