/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { GetMangaIdChaptersOrder } from "./getMangaIdChaptersOrder";
import type { GetMangaIdChaptersSort } from "./getMangaIdChaptersSort";

export type GetMangaIdChaptersParams = {
  /**
   * Include only chapters from these groups
   * @nullable
   */
  group?: string[] | null;
  /**
   * Exclude chapters from these groups
   * @nullable
   */
  groupx?: string[] | null;
  /**
   * @minimum 0
   * @maximum 500
   * @nullable
   */
  limit?: number | null;
  /**
   * Sort order
   * @nullable
   */
  order?: GetMangaIdChaptersOrder;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   * @nullable
   */
  page?: number | null;
  /**
   * Field to sort by
   * @nullable
   */
  sort?: GetMangaIdChaptersSort;
  /**
   * Include only translated chapter languages
   * @nullable
   */
  tlang?: string[] | null;
  /**
   * Exclude translated chapter languages
   * @nullable
   */
  tlangx?: string[] | null;
  /**
   * Include only these uploaders
   * @nullable
   */
  uploader?: string[] | null;
  /**
   * Exclude these uploaders
   * @nullable
   */
  uploaderx?: string[] | null;
};
