/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GetMangaSort =
  | (typeof GetMangaSort)[keyof typeof GetMangaSort]
  | null;

export const GetMangaSort = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  lastUploadedChapterAt: "lastUploadedChapterAt",
  relevance: "relevance",
  title: "title",
  year: "year",
  rating: "rating",
  views: "views",
  follows: "follows",
  chapters: "chapters",
} as const;
