/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import type { GetReportCategory } from "./getReportCategory";
import type { GetReportOrder } from "./getReportOrder";
import type { GetReportSort } from "./getReportSort";
import type { GetReportStatus } from "./getReportStatus";

export type GetReportParams = {
  category?: GetReportCategory;
  /**
   * @minimum 0
   * @maximum 100
   */
  limit?: number;
  object?: string;
  order?: GetReportOrder;
  /**
   * @minimum 1
   */
  page?: number;
  reason?: string;
  sort?: GetReportSort;
  status?: GetReportStatus;
};
