/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import type { GetUserFollowsMangaContentRatingItem } from "./getUserFollowsMangaContentRatingItem";
import type { GetUserFollowsMangaDemographicItem } from "./getUserFollowsMangaDemographicItem";
import type { GetUserFollowsMangaHasChapters } from "./getUserFollowsMangaHasChapters";
import type { GetUserFollowsMangaOrder } from "./getUserFollowsMangaOrder";
import type { GetUserFollowsMangaReadingStatusItem } from "./getUserFollowsMangaReadingStatusItem";
import type { GetUserFollowsMangaSort } from "./getUserFollowsMangaSort";
import type { GetUserFollowsMangaStatusItem } from "./getUserFollowsMangaStatusItem";
import type { GetUserFollowsMangaTmod } from "./getUserFollowsMangaTmod";
import type { GetUserFollowsMangaTxmod } from "./getUserFollowsMangaTxmod";

export type GetUserFollowsMangaParams = {
  /**
   * Artists to filter by (array of IDs)
   */
  artist?: string[];
  /**
   * Authors to filter by (array of IDs)
   */
  author?: string[];
  availableTranslatedLang?: string[];
  contentRating?: GetUserFollowsMangaContentRatingItem[];
  demographic?: GetUserFollowsMangaDemographicItem[];
  hasChapters?: GetUserFollowsMangaHasChapters;
  /**
   * Original language(s) to include
   */
  lang?: string[];
  /**
   * Original language(s) to exclude
   */
  langx?: string[];
  /**
   * @minimum 0
   * @maximum 100
   */
  limit?: number;
  /**
   * Sort order
   */
  order?: GetUserFollowsMangaOrder;
  /**
   * @minimum 1
   */
  page?: number;
  reading_status?: GetUserFollowsMangaReadingStatusItem[];
  /**
   * Field to sort by
   */
  sort?: GetUserFollowsMangaSort;
  status?: GetUserFollowsMangaStatusItem[];
  /**
   * Tags to include (array of IDs)
   */
  tag?: string[];
  /**
   * Tags to exclude (array of IDs)
   */
  tagx?: string[];
  title?: string;
  /**
   * Mode for tag inclusion
   */
  tmod?: GetUserFollowsMangaTmod;
  /**
   * Mode for tag exclusion
   */
  txmod?: GetUserFollowsMangaTxmod;
  user?: string;
  /**
   * Start of the release year range
   * @minimum 1900
   * @maximum 2100
   */
  yearFrom?: number;
  /**
   * End of the release year range
   * @minimum 1900
   * @maximum 2100
   */
  yearTo?: number;
};
