/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */

export type GroupInternalErrorResponseErrorCode =
  (typeof GroupInternalErrorResponseErrorCode)[keyof typeof GroupInternalErrorResponseErrorCode];

export const GroupInternalErrorResponseErrorCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
