/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * WeebDex API
 * WeebDex is an ad-free, scanlator-first online manga reader providing high-quality, zero-compression images. <br /><br />
Contact: [delta@weebdex.org](mailto:delta@weebdex.org) or join our [Discord Server](https://discord.gg/syp3a6Eucq).<br /><br />
All API endpoints have a global rate limit of 5 requests per second per IP. <br />
To avoid future issues, include the Origin: https://weebdex.org and Referer: https://weebdex.org/ headers when making API requests.<br/>
 * OpenAPI spec version: 1.2.0
 */
import type { Demographic } from "./demographic";
import type { MangaFollowAltTitles } from "./mangaFollowAltTitles";
import type { MangaFollowRelationships } from "./mangaFollowRelationships";
import type { ReadingStatus } from "./readingStatus";

export interface MangaFollow {
  alt_titles?: MangaFollowAltTitles;
  content_rating?: string;
  created_at?: string;
  deleted_at?: string;
  demographic?: Demographic;
  description?: string;
  followed_at?: string;
  id?: string;
  language?: string;
  last_chapter?: string;
  last_volume?: string;
  locked?: boolean;
  published_at?: string;
  reading_status?: ReadingStatus;
  relationships?: MangaFollowRelationships;
  state?: string;
  status?: string;
  title?: string;
  updated_at?: string;
  version?: number;
  year?: number;
}
