/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { MangaChapterFeedRelationships } from "./mangaChapterFeedRelationships";

export interface MangaChapterFeedItem {
  /** @nullable */
  chapter?: string | null;
  created_at?: string;
  id: string;
  is_full?: boolean;
  /** @nullable */
  is_unavailable?: boolean | null;
  language?: string;
  published_at?: string;
  relationships?: MangaChapterFeedRelationships;
  /** @nullable */
  source_id?: string | null;
  /** @nullable */
  title?: string | null;
  updated_at?: string;
  /** @nullable */
  version?: number | null;
  /** @nullable */
  volume?: string | null;
  [key: string]: unknown | null;
}
