/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Suicaodex API
 * WeebDex API đè tem, ăn quả úp bô nên không backup kịp data.

Phải gì ạ? Phải chịuuuuuu....
 * OpenAPI spec version: 1.0.0
 */
import type { ScanlationGroupGroup } from "./scanlationGroupGroup";

export interface ScanlationGroup {
  group: ScanlationGroupGroup;
  id: string;
  name: string;
  [key: string]: unknown | null;
}
